### ISSUE TITLE
charts: allow setting user password via environment variable

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#10]
This variable should be `S3GW_ADMIN_PASSWORD`, and will only be relevant on initial deployment of s3gw.

**Comment by jhmarina** [comment]
@m-ildefons will look into it.

**Comment by jhmarina** [comment]
This may already be implemented in the helm chart. @m-ildefons will look into

**Comment by m-ildefons** [comment]
This issue can be closed. The helm chart provides a mechanism to configure the initial access credentials with the configuration keys `accessKey` and `secretKey`. As such, the s3gw can be deployed with custom keys like this:
`helm install s3gw s3gw-charts/s3gw --set accessKey=foo,secretKey=bar`
