### ISSUE TITLE
rgw/sfs: implement chown rest entrypoint

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#118]
### What needs to be done

see upstream issue: https://tracker.ceph.com/issues/57569

### Why it needs to be done

this is blocking link/unlink actions with `sfs` backend 

### Additional Information

this issue will be first submitted upstream and then ported downstream

**Comment by jhmarina** [comment]
Let's push this to post beta

**Comment by giubacc** [comment]
Probably not worth to go further with this item. We didn't use the chown feature in the end.

**Comment by jecluis** [comment]
Closing. Reopen if the need arises.
