### ISSUE TITLE
CI/CD: run stress tests against nightly container

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#12]

**Comment by giubacc** [comment]
@m-ildefons @irq0 as far as you know, are we already doing something similar currently?

**Comment by m-ildefons** [comment]
We're not. Stress testing is something we haven't touched at all afaik.

What we're doing is running s3-tests (which are functional tests, not stress tests).

**Comment by giubacc** [comment]
ok, this needs a discussion how do we want to stress test s3gw's components.
we need also to understand how do we want to export and present results produced by this activity.

**Comment by irq0** [comment]
What is a *stress test* exactly? 

A benchmark that runs the system to saturation? Randomized / parameterized testing and verification? Tests with failure injection?

**Comment by asettle** [comment]
We don't like stress tests
