### ISSUE TITLE
blog: An introduction to s3gw

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#138]
Write an introductory article on the S3 Gateway. It doesn't have to be too extensive but needs to include relevant information. 

**Ideas for the article structure**

- Explain what we’re doing and not in terms of features
- Use case with Longhorn
- Performance benchmark vs Minio
- About the UI
  - screenshots
  - management stuff 
- Explain the next steps for the project
- CTA to gather feedback

**Comment by giubacc** [comment]
done
