### ISSUE TITLE
CI/CD: run s3tests against nightly container

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#14]
### What needs to be done

Make sure all s3tests are executed against the nightly build. The results should be collected (ideally including logs) and made available in human consumable format.

This should serve as automatic analysis of our progress of implementing the S3 API's behaviour.

### Acceptance Criteria

- All s3test executed against the nightly container
- Results available in human consumable format (e.g. s3gw-status repo's static web page)
- (optional) full log collection

### Additional Information

https://github.com/aquarist-labs/s3gw/pull/490

**Comment by jhmarina** [comment]
There's a draft PR by @irq0 implementing the tool: https://github.com/aquarist-labs/s3gw/pull/528

**Comment by asettle** [comment]
Remind Moritz in a week that if this isn't done by then that it's all his fault

**Comment by jecluis** [comment]
I suspect this has been achieved through the s3tr effort, in particular #528 and subsequent PRs.

@m-ildefons and @irq0 can you confirm whether s3tr is being run against the nightly?

**Comment by m-ildefons** [comment]
Not s3tr, but s3tests are being run: https://github.com/aquarist-labs/s3gw/blob/ae9d30fa88547f158b0946777ca44c3d9c639c3d/.github/workflows/nightly.yaml#L109

**Comment by jecluis** [comment]
I think it's safe to consider this done then.
