### ISSUE TITLE
rgw/sfs: update the way admin rest handlers are registered

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#141]
When we will sync with upstream we will have to update the way admin rest handlers are registered, now this is done inside rgw_main.cc and this is valid for all backends:

```
if (apis_map.count("admin") > 0) {
    RGWRESTMgr_Admin *admin_resource = new RGWRESTMgr_Admin;
....
    rest.register_resource(g_conf()->rgw_admin_entry, admin_resource);
  }
```

on upstream this has been moved in a specific way so that a be must do this work overriding:

`virtual void register_admin_apis(RGWRESTMgr* mgr) override { };`

failing to do this makes all admin apis return http code: `405`

**Comment by jecluis** [comment]
This issue has been addressed during the last rebase and subsequent patches.
