### ISSUE TITLE
CI/CD: Automate changelog generation from the git log

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#149]
### What needs to be done

We should have automation to generate a changelog from the git log. 

### Why it needs to be done

We are currently creating the changelogs manually. This means that many times, there's Doing this manually isn't something we should be done by hand and especially not something worth putting in git history.

### Acceptance Criteria

The changelog for our different repositories is generated automatically

**Comment by irq0** [comment]
This seems to predate our wiki approach https://github.com/aquarist-labs/s3gw/wiki.

Some releases include generated changelogs https://github.com/aquarist-labs/s3gw/releases/tag/v0.15.0
