### ISSUE TITLE
Rebase upstream (January 2023)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#171]
### What needs to be done

We need to rebase https://github.com/aquarist-labs/ceph & upstream.

**Comment by tserong** [comment]
You should be good to drop https://github.com/aquarist-labs/ceph/pull/53/commits/61bb5e4da01bd26f14a658d44f9b570259723110 during the rebase, as the fmt9 FTBFS has since been fixed in upstream main.

**Comment by jecluis** [comment]
Current rebased branch can be found at

> https://github.com/aquarist-labs/ceph/tree/s3gw-next-2023-01

This will be tested soon, and, if nothing evil crops up, will soon be replacing the current `s3gw` branch.

**Comment by jhmarina** [comment]
The rebase has been completed
