### ISSUE TITLE
rgw/sfs: The `mtime` field of buckets is not populated

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#174]
I'm not sure if this is a regression, but with the latest `s3gw` container the [mtime field](https://github.com/aquarist-labs/s3gw-ui/blob/main/src/app/shared/services/api/admin-ops-bucket.service.ts#L26) of the buckets response object (via Admin Ops API) is not populated any more. It only contains `0.00000`.

The API call is: `http://localhost:4300/admin/bucket?stats=true`

![Bildschirmfoto vom 2023-03-09 16-00-30](https://user-images.githubusercontent.com/1897962/224064523-d6ef04ff-dfc4-4e3c-a00c-5c0571839348.png)

![Bildschirmfoto vom 2023-03-09 16-00-22](https://user-images.githubusercontent.com/1897962/224064567-2536e314-1e74-41f5-bdcd-993743045aca.png)

**Comment by asettle** [comment]
@jecluis is fairly certain this is fixed, is going to investigate

**Comment by jecluis** [comment]
this is still the case:

```json
  {
    "bucket": "foobar",
    "num_shards": 1,
    "tenant": "",
    "zonegroup": "",
    "placement_rule": "default",
    "explicit_placement": {
      "data_pool": "",
      "data_extra_pool": "",
      "index_pool": ""
    },
    "id": "foobar.1697691030534392846",
    "marker": "foobar.1697691030534392846",
    "index_type": "Normal",
    "owner": "testid",
    "ver": "",
    "master_ver": "",
    "mtime": "0.000000",
    "creation_time": "2023-10-19T04:50:30.534392Z",
    "max_marker": "",
    "usage": {},
    "bucket_quota": {
      "enabled": false,
      "check_on_raw": false,
      "max_size": -1,
      "max_size_kb": 0,
      "max_objects": -1
    }
  }
```
