### ISSUE TITLE
UI: logged in UX for admin/regular users

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#175]
### What needs to be done

Mock up a UX where the user can easily differentiate between an admin and a system user. Implement aftewards.

### Why it needs to be done

The only way for the user to know whether they are on the admin or regular user view is by the colour of the user icon:

![Bildschirmfoto vom 2022-10-20 18-11-22](https://user-images.githubusercontent.com/2351510/197714854-00be8557-45ce-4a63-82da-bf419870aaaa.png)

This isn't great from an accessibility perspective since it relies solely on colour to convey the user type. 

An idea is to have an administration menu with the usual admin operations.

### Acceptance Criteria

* @jhmarina mocks up a UX
* it is shared with the team & feedback is gathered
* @votdev can then implement it

**Comment by jhmarina** [comment]
The team discussed this and it was decided that we'd implement an admin menu with admin-specific features. We also agreed that this does not need a UX mockup

**Comment by votdev** [comment]
![Peek 2022-11-16 11-32](https://user-images.githubusercontent.com/1897962/202158201-0bb0937a-882e-4b16-b71f-959b1e00f61f.gif)

**Comment by votdev** [comment]
An alternative solution using a toggle button to switch between `user` <-> `admin` mode for users with administration privileges.

![Peek 2022-11-16 14-49](https://user-images.githubusercontent.com/1897962/202198296-a575afbd-6129-4356-afe8-390432a31360.gif)

**Comment by votdev** [comment]
We decided in the meeting to use the implementation that allows toggling the views using a checkbox in the upper top bar.
