### ISSUE TITLE
UI: UX for logging in as administrator

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#177]
### What needs to be done

Mock up a UX that handles both the login and regular user logins.

### Why it needs to be done

Currently, the UX displays a checkbox to log in as an admin. This can lead to confusion since it feels like anyone can log in as an admin.

There are different possible approaches to fix this. 

#### Best approach from a UX perspective

Testing whether the credentials are an admin or not and then logging in is the ideal option since it allows for removing the checkbox. We may not need a mockup.

### Acceptance Criteria

* @jhmarina mocks up a UX
* it is shared with the team & feedback is gathered
* @votdev can then implement it

**Comment by jhmarina** [comment]
<s>Testing wether the credentials are admin or not and then logging in is the ideal option, since it allows for removing the checkbox. We may not need a mockup.</s>

**Comment by votdev** [comment]
![Peek 2022-11-16 11-32](https://user-images.githubusercontent.com/1897962/202158240-d41571bf-cf99-4ec9-b313-3f846d1931bc.gif)
