### ISSUE TITLE
CI/CD: Run benchmark against PR's container

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#18]

**Comment by giubacc** [comment]
@jhmarina I'm a bit concerned that doing this kind of activity per PR could be too much complex and resource consuming.

**Comment by asettle** [comment]
Marcel volunteered because he'd love to have this "eventually" :)

**Comment by irq0** [comment]
Done. Add label ci/build-s3gw-image to a PR. Container gets built and pushed to quay. The benchmark system picks it up shortly after and runs the quick and comprehensive suite.
