### ISSUE TITLE
rgw/sfs: Support new style buckets

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#189]
### What needs to be done

We need to investigate further, find out if RGW supports buckets on the hostnames, and how we'd do it via ingress.

### Additional Information

https://confluence.suse.com/display/SUSEEnterpriseStorage/2022-10-13+-++s3gw+Strategy+Meeting

**Comment by asettle** [comment]
This is the current default within the helm chart - closing as done
