### ISSUE TITLE
CI/CD: Build & run smoke tests as merging criteria

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#19]

**Comment by m-ildefons** [comment]
We do run smoke tests from aquarist-labs/s3gw-tools/tests/s3gw-smoke-test.sh as merge criteria:
https://github.com/aquarist-labs/ceph/blob/def7eaa4f236576dc9cab6fcaf9c576c18fcebb9/.github/workflows/test-radosgw.yml#L80
