### ISSUE TITLE
Implement certificate management

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#193]
### What needs to be done

Implement certificate management.

### Why it needs to be done

To allow accepting SSL connections.

**Comment by giubacc** [comment]
@m-ildefons I'm also making experiments with certificate management since it is a hot topic for the integration with Epinio.
Let's remember to coordinate before proposing PRs.

**Comment by giubacc** [comment]
I suggest to go with: https://cert-manager.io/
This is already used by Epinio project and Rancher

**Comment by Martin-Weiss** [comment]
The helm chart should allow to specify the clusterIssuer or Issuer that should be used with the ingress so that the SSL certificates can be created and maintaied automatically by cert-manager.
