### ISSUE TITLE
chart: Suggest a namespace when installing via Rancher app catalog

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#197]
Right now the namespace field is empty, but i find it more user friendly if it is pre-filled with `s3gw` for example.
![Bildschirmfoto vom 2022-11-02 10-48-02](https://user-images.githubusercontent.com/1897962/199458390-2c766037-83ac-4d22-8e67-2bbcfd421c78.png)

Alternatively fix it to `s3gw` as it is done by the `Traefik` app.
![Bildschirmfoto vom 2022-11-02 10-47-47](https://user-images.githubusercontent.com/1897962/199458356-b42bb3fc-a0ad-45c3-b52e-3f5570ebb052.png)

**Comment by jecluis** [comment]
We will most likely drop the chart from the Rancher Marketplace once LH 1.6 is out. We'll not further develop or enhance the current chart.
