### ISSUE TITLE
s3gw: try not having traefik as a requirement, use whatever

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#2]
We should probably allow the user to use whatever ingress they have. As someone else said,

> Ideally, we serve the requests sent to a service type LoadBalancer or an ingress provided by the platform vs needing another bulky component…

**Comment by jecluis** [comment]
@m-ildefons @giubacc do you have an opinion on this?

**Comment by m-ildefons** [comment]
The chart doesn't require Traefik per se (anymore), but we don't support any other ingress controllers at the moment. You can use the chart with other ingress controllers by not deploying an ingress resource through the chart and just creating your own after deploying the s3gw without an ingress.
