### ISSUE TITLE
[BUG] Chart versions are not visible in Rancher App Catalog

### ISSUE THREAD

**Issue by abonillabeeche** [s3gw-tech/s3gw#213]
**Describe the bug** A clear and concise description of what the bug is.
When a new chart of s3gw is released, only the latest version is visible.

![Screenshot 2022-11-11 at 10 57 38 AM](https://user-images.githubusercontent.com/5146963/201382800-4d6a2cff-9f98-4731-beee-d1785d1f266c.png)

**To Reproduce** Steps to reproduce the behavior:

1. App the s3gw repo
2. Release a new version
3. Refresh the repo
4. Check the Chart/App or try to downgrade

**Expected behavior** 
All "supported" versions should be listed or at least the previous or downgrade-able-to versions.

for example
![Screenshot 2022-11-11 at 10 58 25 AM](https://user-images.githubusercontent.com/5146963/201383494-7fcf8b67-4a55-46cf-99a5-30ddb63db753.png)

**Comment by abonillabeeche** [comment]
https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#chart-directory-structure

**Comment by jhmarina** [comment]
Adding the http repository sorts this issue out. We will update the documentation to inform users
