### ISSUE TITLE
docs: Use templates for PRs, Bugs, Issues & Feature Requests

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#22]
### What needs to be done

Create and  implement an issue template for:
* Feature requests
* Issues
* Bugs
* PRs

it would need to be implemented in the following repositories:
* Main repository
* Charts
* UI

### Why it needs to be done
Currently, we're not using any template for issues or bugs. In fact, we've defined many issues in the past with barely any information on them. This makes it difficult to understand what some of these tasks are about.

implementing a simple issue template for new features & bugs should allow for more clarity when defining the scope of a task.

### Acceptance Criteria

1. A user opens an issue
2. The user is able to choose an issue template

### Additional Information

* Suggested template for new features (currently being used in this issue) https://blog.codecentric.de/en/2022/01/jira-template-user-story-tasks-bugs/
* Basic bug template: https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md

**Comment by jhmarina** [comment]
~~The first step for this issue should be to open a PR with an ADR proposal & then, once there is consensus, implement the templates~~

In other to speed up the process, opening a PR should suffice. Feedback can be gathered on the PR itself. If we need an ADR after the fact, it also makes sense

**Comment by jhmarina** [comment]
Github already includes issue templates: https://github.com/aquarist-labs/s3gw/issues/templates/edit

**Comment by m-ildefons** [comment]
Thanks Jesus, I'll close this one since it's done.
