### ISSUE TITLE
rgw: skip upstream commit [multivalue-domain-config] on next rebase

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#220]
### What needs to be done

This upstream [PR](https://github.com/ceph/ceph/pull/48554) must be skipped on the next rebase.
We are anticipating the merge downstream with this [PR](https://github.com/aquarist-labs/ceph/pull/66) .

**Comment by jecluis** [comment]
I'm not sure whether this patchset was skipped during the rebase. @irq0 Might be a good idea to look out for it on the next one.

**Comment by votdev** [comment]
Closing because downstream PR has been merged.
