### ISSUE TITLE
charts: describe what s3gw is in the readme

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#224]
As it was pointed out on slack about the chart in ArtifactHub,

> On that page is seems to assume one know what s3gw is and that they are just looking to install it. Should the readme for the chart tell people what it is and the cases where they will find it useful?

I agree with the sentiment and believe the chart should describe what s3gw is, instead of just instructions on how to install.

**Comment by votdev** [comment]
Maybe use the introduction from https://www.suse.com/c/rancher_blog/introduction-to-s3gw/.
