### ISSUE TITLE
UI: Support folders in object explorer

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#241]
Blocked by:
- ~~https://github.com/aquarist-labs/s3gw/issues/306~~
- ~~https://github.com/aquarist-labs/s3gw/issues/261~~

References:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html
- https://blog.skeddly.com/2020/09/amazon-s3-folders-demystified.html

**Comment by jecluis** [comment]
related dependency: https://github.com/aquarist-labs/s3gw/issues/261
