### ISSUE TITLE
rgw/sfs: Don't leak internal identifiers

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#25]
We currently design around per-bucket sequential version ids. Handing those back to the user has security implications. See for example https://wiki.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References

As object versions are opaque data, we can map internals to pretty much whatever we want. Either custom or something like https://hashids.org

**Comment by jhmarina** [comment]
Closing because this doesn't apply anymore. We might reopen the issue if needed.
