### ISSUE TITLE
UI: Enable versioning in the UI

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#254]
### What needs to be done

Enable versioning in the UI. We have a checkbox to enable it, but this will involve creating an interface to visualize different versions of a file and relevant data. We may need to mock the UI up before implementing.

### Why it needs to be done

Versioning is enabled in the backend and can be managed via the CLI. Having it in the UI should also be an option.

### Acceptance Criteria

The user can manage file versioning through the UI.

### Additional Information

n/a

**Comment by votdev** [comment]
Duplicate of https://github.com/aquarist-labs/s3gw/issues/271.

**Comment by votdev** [comment]
@jhmarina Can we close that?
