### ISSUE TITLE
UI: Object version management: Enable object delete/undelete in the UI

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#255]
### What needs to be done

Enable undeleting a file in the UI. We may need to mock the UI up before implementing it.

### Why it needs to be done

Undeleting is enabled in the backend and can be handled via the CLI. Having it in the UI should also be an option.

### Acceptance Criteria

The user can manage file versioning through the UI.

### Additional Information

n/a

**Comment by votdev** [comment]
Blocked by https://github.com/aquarist-labs/s3gw/issues/539

**Comment by jhmarina** [comment]
@votdev I'm changing the status to Blocked for the issue
