### ISSUE TITLE
[FR] Application data backup operator

### ISSUE THREAD

**Issue by agracey** [s3gw-tech/s3gw#263]
**Is your feature request related to a problem? Please describe.**

Having to write a custom backup for each application's data can be annoying and easy to make mistakes. Backing up the full PVC (as planned with LH) is really nice but sometimes it can be a bit of overkill. 

**Describe the solution you'd like** A clear and concise description of what you want to happen.

It might be interesting to allow an admin to label pods with a list of directories and schedule to be synced with an s3 bucket. The operator could then inject an ephemeral container into the pod for the sync on a schedule. 

**Additional context** Add any other context or screenshots about the feature request here.

I'd imagine this is likely a new component but I think it could be really interesting in the context of the s3gw project.

**Comment by m-ildefons** [comment]
Hi,
thanks for the feature suggestion, it sounds really interesting. However there already exists [K8up](https://k8up.io/k8up/2.5/index.html). How would the proposed operator be different from that?

**Comment by agracey** [comment]
I had never seen that before (or if I did, I assumed it was k3sup -- too many projects that all sound alike) 

Thank you for the pointer! this feature alone makes me happy: https://k8up.io/k8up/2.5/how-tos/application-aware-backups.html

**Comment by agracey** [comment]
Closing as un-needed 😄
