### ISSUE TITLE
csr: radosgw-admin as rest client vs radosgw to configure cross-site replication

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#27]
Current implementation of cross-site replication relies on the configuration produced by `radosgw-admin`.
The tool is directly writing the configuration on rgw pools inside rados.
We need a tool to be able to write csr configuration on sqlite tables that will be then read by s3gw.
An approach that could be interesting to implement is to modify `radosgw-admin` tool and realize with it a rest-client talking to  s3gw.
The configuration would, in this way, be written exclusively by s3gw.
This approach could have some advantages:

- The access to internal sqlite storage is realized only by s3gw and not by another tool that is modifying a critical part of the system.
- Rados admin implements already a huge part of the client, we should "simply" modify the handlers that are writing to the rados pool and inject there the rest-api calls vs s3gw.
- Power users or system administrators could use `radosgw-admin` as a tool to quickly program configurations.
- The system could be programmed to be provisioned with an initial configuration.
- This is an advanced tool for developers.
- This can be used to program tests related to governance/administrative section and also to program other non-admin tests that would require a certain scenario.

Another implementation proposal [here](https://github.com/aquarist-labs/s3gw-core/issues/113)

**Comment by jhmarina** [comment]
@giubacc it looks like the other proposal was deleted when we migrated the issues to the new repo

**Comment by jhmarina** [comment]
Closing this issue as it is a research issue and it the research seems to have been conducted.
