### ISSUE TITLE
UI: Object versioning

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#271]
### What needs to be done

Information tba.

**Comment by jecluis** [comment]
@votdev I was under the impression we already have object versioning support on the UI. What exactly is missing there? Listing versions? If so, can we make this issue clearer, or create new issues for that?

**Comment by votdev** [comment]
Versioning is available since `0.6.0`:

- https://github.com/aquarist-labs/s3gw-ui/pull/54
- https://github.com/aquarist-labs/s3gw-ui/pull/57

**Comment by jecluis** [comment]
@jhmarina can we close this one?
