### ISSUE TITLE
csr: figure out how cross site replication is working with rados

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#28]
We need to setup 2 classic ceph clusters and figure out how `radosgw-admin` tool is interacting with `radosgw`.
We need to identify what configuration is needed by `radosgw` and what other "not-configuration" resources are needed as well.

**Comment by jecluis** [comment]
I believe this is something out of scope for now, and the issue should be closed.

**Comment by giubacc** [comment]
out of scope for now, closing.
