### ISSUE TITLE
rgw/sfs: A `getObject` does not provide a valid `LastModified` date

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#289]
The `LastModified` field in the [getObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property) response and the `Last-Modified` HTTP header is not set correct, it always contains `Thu Jan 01 1970 01:00:00 GMT+0100`. In a [listObjects](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) call the `LastModified` field is correctly set.

![Bildschirmfoto vom 2023-03-27 17-16-33](https://user-images.githubusercontent.com/1897962/227984821-06a72903-e8c7-4c1a-a705-5a98c472857c.png)

![Bildschirmfoto vom 2023-03-27 17-16-11](https://user-images.githubusercontent.com/1897962/227984866-4ea1fde0-2537-49cb-928f-0454c7ae82a8.png)

**Comment by jhmarina** [comment]
@votdev will revise the issue and add more info to it
