### ISSUE TITLE
rgw/sfs: support multipart copy

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#3]
https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html

**Comment by jecluis** [comment]
turns out multipart copy exists as long as multipart uploads exist. Internally, rgw simply reads from one object and does a multipart write to another. Closing this as achieved by default.

**Comment by jhmarina** [comment]
> turns out multipart copy exists as long as multipart uploads exist. Internally, rgw simply reads from one object and does a multipart write to another. Closing this as achieved by default.

That's good news then!
