### ISSUE TITLE
[BUG] data won't persist after reutilizing PVC on redeployment

### ISSUE THREAD

**Issue by abonillabeeche** [s3gw-tech/s3gw#301]
**Describe the bug** A clear and concise description of what the bug is.
When reutilizing s3gw-pvc, the new deployment may be clearing the storage device.

**To Reproduce** Steps to reproduce the behavior:

1. Install a version of s3gw specifying the storageclass and device size
2. Create a bucket and upload a file
3. Remove the helm deployment but keep the s3gw-pvc
4. Install s3gw again (I used a newer version)
5. The data and bucket previously created are not visible

**Expected behavior** 
Data should remain available

**Comment by jecluis** [comment]
This is rather curious. Is the pvc being used by the new deployment the same? Was this a pvc provided by longhorn?

**Comment by jecluis** [comment]
We discussed this issue today, and the consensus is that by uninstalling the helm chart you are indeed losing the claim you had on the s3gw volume. The reasoning is that by running a `helm uninstall` you are essentially deleting the resources in the deployment, and that includes the claim. When creating a new deployment, kubernetes will not reuse an existing volume for a new claim.

I'm considering this as the s3gw chart behaving as expected. Let me know if you disagree.
