### ISSUE TITLE
Provide a FUSE file system that allows to access the buckets/objects

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#302]
It would be useful in some situations to be able to access the buckets/objects via file system.

Maybe support the basic functions:
- Create
- Modify
- Delete
- 
The file system will display the latest versions. If a bucket/object is modified, it will create a new version under the hood.

**Comment by jecluis** [comment]
A quick search on google shows that there is at least one [reasonably large, active project](https://github.com/s3fs-fuse/s3fs-fuse) doing this. I see no reason why this would not work with s3gw itself, although I didn't check it out in detail.

I think this feature request is out of scope for the s3gw project.
