### ISSUE TITLE
rgw/sfs: add support for delimiter when listing objects

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#306]
Aside from `prefix` S3 offers `delimiter` to list objects in a bucket in different ways. 

For example, with the following objects in the bucket:
```bash
directory/directory/file
directory/file
file
```
if we list with delimiter = `/` the GW should reply with:
```
Contents:
file

CommonPrefixes:
directory/
```

**Comment by votdev** [comment]
This may be helpful for https://github.com/aquarist-labs/s3gw/issues/241.
