### ISSUE TITLE
csr: cross-site replication feature description

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#32]
Cross-site replication represents a macro area of investigation. 
Here are some initial thoughts about this.
Please note that what follow is based on the assumption that only 1 site is active and accepting connections from s3gw clients.
Other sites must be intended as passive sites that are not accepting connection from s3gw clients.
One passive site could become active if the primary site become unavailable.
Cross replication could deal with moving huge pieces of data between sites that are geographically located in different continents. 
One motivation could be, for example, implement a disaster resiliency policy with a certain grade of flexibility.

Replication could be thought in 2 different fashions:

1. Format aware replication
2. Format unaware replication

Case 1 happens when the replication mechanism knows the underlying data's format and could take advantage of this. 
Case 2 should basically mean blindly moving the content of a PV, regardless what is its storage format.

From the user perspective, one could be interested enabling a cross site replication in different ways.
Here some examples:

### Cold replication

Cold replication happens when the s3gw is offline and the content of a PV is known guaranteed to be stable for the entire duration of the replication process.
This is a snapshot approach: data is moved entirely on another location and no knowledge of the underlying format is needed.
Because the amount of data to be transmitted when snapshotting a PV could be all but negligible, this approach could be feasible only if the transport medium between sites guarantees a previously measured performance.
For example, if it were known that the system is not used between 2am and 4am and the line is able to transmit an amount of data in that window, two clusters could use this strategy to replicate data.
If for some reason, replication should fail in the allowed replication window, s3gw could be prevented to be started. This because, maybe, it is more critical ensuring the 2 sites to have differences not exceeding one day. 
Variations to this approach can be limited only by imagination, but the central point here is that the process must be done when s3gw is offline and it can be extremely slow to complete.
This approach could be implemented by a component different from radosgw, and probably this would be the preferred way.

### Hot replication

Hot or live replication happens when the s3gw is online and the content of a PV changes when the replication process takes place.
Two sites constantly maintain the same image by sending variations when these happen.
This is an incremental approach, based on transmitting variations; incremental phase could follow an initial snapshot transmission.
Based on the initial snapshot size, the system could be forced to stay offline for more or less time.
After that initial transmission the 2 sites could be maintained aligned without any other downtime. 
Because this approach probably implies that the two sites must be reasonably aligned in a constrained temporal window, it is likely to expect that s3gw must be prevented to accept modifying connections after a certain amount of data is enqueued towards the other site.
This approach could be still partially implemented by a different component but probably a communication protocol with radosgw has to be realized.

**Comment by jecluis** [comment]
Thanks for writing this up :)

I think the terms "cold replication" and "hot replication" are going to lead people in error. What you are describing is "offline" and "online" replication. I don't think we care about the former -- that's something outside the scope of s3gw. We may eventually provide steps on how to do that, but that's essentially a backup.

I do think we will be interested in the latter though, "online replication". RGW already supports this with multisite. I don't think we'll need to create a new approach to achieve this, but we will want to look into how we can leverage the existing multisite implementation to achieve our goal.

**Comment by l-mb** [comment]
I think what would make sense is investigating what would be necessary to make RGW's multi-site/zone features work with `s3gw` as one of the end points, but I'm very convinced we should not implement something indepedently ourselves.

**Comment by jhmarina** [comment]
Closing this issue since this feature is actually implemented in Ceph

**Comment by jhmarina** [comment]
Just to clarify, we've created an Epic and will work on CSR in the future: https://github.com/aquarist-labs/s3gw/issues/259
