### ISSUE TITLE
rgw/sfs: Deleting a bucket with objects does not throw `BucketNotEmpty` error

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#325]
When deleting a bucket which contains several objects, it is expected that a `BucketNotEmpty` is thrown when trying to delete the bucket via AdminOps API. The bucket should be deleted only if the argument `purge-objects` is set. Check out the API docs [here](https://docs.ceph.com/en/latest/radosgw/adminops/#remove-bucket).

The UI has added this feature by https://github.com/aquarist-labs/s3gw-ui/pull/134. With a connected Ceph RGW this works as expected.

**Comment by giubacc** [comment]
@jhmarina this seems a bit concerning issue.
I suggest to give this priority for the upcoming releases.

**Comment by 0xavi0** [comment]
The s3test **test_bucket_delete_nonempty** is the one testing this on the backend
