### ISSUE TITLE
CI/CD: Automate s3tests

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#351]
### What needs to be done

Automate running the `s3tests`. Since we're aiming at doing compliance testing in Q2, this is a requirement. Also we want to display the test results in https://aquarist-labs.github.io/s3gw-status/#/s3tests

### Why it needs to be done

Currently, there is no way of testing release candidates other than on a developer's workstation. We want to implement an automated process, which will also help us pave the way for the latter implementation of compliance testing (compliance with the S3 API spec)

**Comment by jecluis** [comment]
@m-ildefons and @irq0 - this is already implemented afaict, but I may be missing some nuance of this issue?
