### ISSUE TITLE
Use Rancher Manager ingress

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#352]
We want to ensure that the s3gw integrates with Rancher Manager. 

When we started the project we identified k3s as one of our targets and used Traefik for managing ingresses.
This is an issue when setting the s3gw up in Rancher Manager since it uses its own.

We want to scope the user needs in terms of ingresses so that we can plan the next steps and implement features accordingly.

This is a research issue that will also involve a call with stakeholders.

**Comment by giubacc** [comment]
I gave a look at the Epinio chart implementation; I think that we can start with that approach in the first instance.
We are currently handling CORS at ingress level; this could represent a problem.
We should start investigating if we can handle CORS at `radosgw` level. 
Once ascertained that we can do the same things we are doing today handling CORS at `radosgw` level, we can proceed with this item.

**Comment by jhmarina** [comment]
Issue for the investigation https://github.com/aquarist-labs/s3gw/issues/275. I will now close this issue.
