### ISSUE TITLE
charts: make domain variables mandatory during installation  

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#354]
### What needs to be done

Now `publicDomain` and `ui.publicDomain` both default to `howdoi` fake domain.
The user should be forced to fill these values during installation as Rancher and Epinio are already doing. 
We should mention in documentation that `howdoi` can be used for demo environments like Epinio is [doing](https://docs.epinio.io/installation/magicDNS_setup).

### Why it needs to be done

defaulting to `howdoi` is not acceptable.

**Comment by m-ildefons** [comment]
Enforcement of sensible user input for the domain values is implemented by f1c8a46955aaedab2302b6dfa0595186c63a75e7 and 5f5b772e573be00a5239b1b10d8a4638bc3ec198 already. Still in progress is writing a quickstart guide for a demo setup using sslip.io or similar.

**Comment by jhmarina** [comment]
Documentation needs to be written for it. Epinio had similar documentation we may be able to leverage.

**Comment by jhmarina** [comment]
Closing this issue as the issue has been addressed. I will create a separate one for the documentation.
