### ISSUE TITLE
rgw/sfs: garbage collection enhancements

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#357]
The garbage collection implementation should be enhanced with the following features:

- it should work independently on both deleted bucket and deleted objects.
- it should allow a retention policy for the files on the volume of eligible buckets/objects:
  - `DELETE_IMMEDIATELY`
  - `DELETE_AFTER_RETENTION_PERIOD`
  - `KEEP`

These policies apply `asynch` when a GC cycle run.
We must also address the case of an operation (eg a put of an object) that fails, but it would not, if the logically removable occupied space, had been eliminated by a GC run.
In this case, the failing operation should be retried after the system automatically performs a `sync` GC run.

**Comment by jecluis** [comment]
> - it should work independently on both deleted bucket and deleted objects.

Can you expand what you mean by this?

> 
> - it should allow a retention policy for the files on the volume of eligible buckets/objects:
> 
>   - `DELETE_IMMEDIATELY`
> 
>   - `DELETE_AFTER_RETENTION_PERIOD`
> 
>   - `KEEP`

While feasible, I'm not sure this is actually a good idea. The greatest benefit of doing asynchronous garbage collection is to, ideally, perform removal operations when the system is not under stress as to not significantly impact performance.

By allowing immediate removals, we would be saying removal is more important than performance, no matter what.

Given the effort of implementing GC policies, and given these may have a negative effect on performance, for potential corner use-cases, I'm not sure we get a particular benefit by dedicating time to this versus making the GC smarter.

**Comment by giubacc** [comment]
> > * it should work independently on both deleted bucket and deleted objects.
> 
> Can you expand what you mean by this?

From my understanding in a discussion with @0xavi0; the current implementation considers only deleted buckets; but eg: if an object is deleted inside a living bucket, that object is not taken in consideration by the GC.
I think GC should be improved to detect both deleted buckets and deleted objects independently. 





> While feasible, I'm not sure this is actually a good idea. The greatest benefit of doing asynchronous garbage collection is to, ideally, perform removal operations when the system is not under stress as to not significantly impact performance.
> 
> By allowing immediate removals, we would be saying removal is more important than performance, no matter what.
> 
> Given the effort of implementing GC policies, and given these may have a negative effect on performance, for potential corner use-cases, I'm not sure we get a particular benefit by dedicating time to this versus making the GC smarter.

Not sure we are on the same line here: what I mean here is that these policies apply asynchronous when the GC run.
In this context, for example, `DELETE_IMMEDIATELY` is a policy that is performed by the GC thread when a cycle occurs.
So, in this case, the GC would not only mark a record in the database as deleted, but it would also immediately physically delete the files linked to that record.
These policies are NOT performed by the "user" thread that is, for example, trying to PUT a new object.
When to run a GC cycle is another story, and yes, that could be done with other, possibly, smarter policies than a fixed timer.

I don't think there are corner-use-cases or mainstream-cases; the user should the ultimate decider and he should be free to setup the gateway based on his personal needs based on his workload and his environment setting.
The concept of "benefit" is very much what the user feels as "benefit".

**Comment by jecluis** [comment]
> > > * it should work independently on both deleted bucket and deleted objects.
> 
> > 
> 
> > Can you expand what you mean by this?
> 
> 
> 
> From my understanding in a discussion with @0xavi0; the current implementation considers only deleted buckets; but eg: if an object is deleted inside a living bucket, that object is not taken in consideration by the GC.

Gotcha. That wasn't my understanding of the current GC implementation, but I agree that we need to ensure individual objects are properly garbage collected.

> Not sure we are on the same line here: what I mean here is that these policies apply asynchronous when the GC run.
> 
> In this context, for example, `DELETE_IMMEDIATELY` is a policy that is performed by the GC thread when a cycle occurs.
> 
> So, in this case, the GC would not only mark a record in the database as deleted, but it would also immediately physically delete the files linked to that record.

I'm not sure I understand what you mean. Is this about ensuring objects are removed on a GC cycle, regardless of whether we reach the GC's cycle timeout?

> I don't think there are corner-use-cases or mainstream-cases; the user should the ultimate decider and he should be free to setup the gateway based on his personal needs based on his workload and his environment setting.
> 
> The concept of "benefit" is very much what the user feels as "benefit".

But there are corner cases and general usage cases. Every software has those. That's why some softwares are better equipped to do some things versus others. And while the user should be free to do whatever they want with the software, it is still up to us to define what has priority over other things. If something is deemed an edge case, its priority is likely smaller than the general use case.

I understand that may not be a popular opinion with some users, but it's the reality of software development.

In the end, it's up to @jhmarina to define which things get prioritised over which.

**Comment by giubacc** [comment]
> I'm not sure I understand what you mean. Is this about ensuring objects are removed on a GC cycle, regardless of whether we reach the GC's cycle timeout?

I mean: suppose a GC cycle is occurring, the GC thread is running and checking for deleted object.
An object is found eligible to be deleted, if the policy is `DELETE_IMMEDIATELY` the GC thread removes the records from the sqlite table AND also deletes the files (associated to that object) from the filesystem.
Otherwise if the policy is `KEEP` it only removes the records from the database but it keeps the files on the filesystem.
Hope this clarifies what I mean.

> But there are corner cases and general usage cases. Every software has those. That's why some softwares are better equipped to do some things versus others. And while the user should be free to do whatever they want with the software, it is still up to us to define what has priority over other things. If something is deemed an edge case, its priority is likely smaller than the general use case.
> 
> I understand that may not be a popular opinion with some users, but it's the reality of software development.

Fair and understandable; mine was just an opinion ;)

**Comment by 0xavi0** [comment]
What would be the use case of keeping the data (files) but deleting the metadata for it?

**Comment by jecluis** [comment]
Good question. I'm also wondering about that. That would essentially leave orphaned files we would not be able to remove at all, other than manually going through all existing files and trying to map them to entries in the database. This would make users very angry at some point, especially in resource constrained environments.

**Comment by giubacc** [comment]
Well, I agree that `KEEP` in these terms makes absolutely no sense.
Removing records && keeping files is something we would NOT want to do.
I was wondering, btw, what is the current implementation? what is the GC thread doing?
One deletes a bucket, GC thread then what is doing? are links to files and database  preserved?

**Comment by jhmarina** [comment]
I'm closing this issue for now since we had a call and defined the next steps for GC. Here is the issue: https://github.com/aquarist-labs/s3gw/issues/393
