### ISSUE TITLE
Ensure crash consistency (Epic)

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#362]
## Rationale
There are plenty of places where we are not ensuring crash consistency, especially by not wrapping metadata operations in transactions. There's the suspicion that other places don't ensure metadata is properly updated only once data is guaranteed to have been written. Other things, like multipart, write data to disk but don't (currently, being worked in #129 ) keep track of said written data in sqlite. And we don't ensure we fsync the written data.

Some of these things are slated to be addressed through planned code changes (e.g., while removing the cache), but still need to be purposefully fixed. Others need proper code reviews of what is, and fixed.

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/363
- [ ] https://github.com/aquarist-labs/s3gw/issues/364
```

**Comment by l-mb** [comment]
Ideally we'd also have a test case for this - run a load/verifying test in one thread and repeatedly `SIGKILL and restart` the s3gw process in another.

That's not ideal because it doesn't fully simulate loss of not-fsync'ed-writes (such as for a hard node outage), but it'd be a start.

**Comment by irq0** [comment]
#363 Atomic Writer (non-multipart PUT) Error Handling and fsync()

**Comment by irq0** [comment]
We should probably start with defining our object state machine #364 and deriving code + tests from that.

**Comment by jhmarina** [comment]
We've broken down this epic into smaller Epics & tasks (mainly bug issues) (https://github.com/aquarist-labs/s3gw/issues/563)
