### ISSUE TITLE
CI/CD: Improve our current CI - Research available options

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#366]
### What needs to be done

Research different avenues on how we should handle our CI. We want to weigh in the different options and come up with a plan. Depending on the outcome of the investigation, we'll have to plan out wether there's budget and how to proceed. these are the options:

- Github offers (as a beta) larger runner instances for paid plans. Given the ease of integration, would that perhaps be an option? Would this give us additional benefits?
- What are the price brackets relevant to us and how much do we estimate would it cost to satisfy our needs on the various common CI solutions (e.g. CircleCI, TravisCI, ...)?
- What are other teams doing/spending on this?
- What's the estimated cost of not doing any of this (long build times --> inefficient, unhappy developers, or having to actually work on the code big time?)
- What would self-maintained Jenkins or self-hosted GH Workers on big cloud VMs cost (both in terms of manpower and direct cost), are there any particularly cheap offers?
- Not using CI: this may be the weakest link as repurposing old hardware for performance tests or other development tasks may not be very helpful. Re-purposing old SES hardware comes at a non-zero cost as someone has to spend time to set it up and maintain it and that breakage is inevitable and time-intense to fix. Plus using old hardware may not even result in relevant data, as performance characteristics do change over the course of half a decade.

### Why it needs to be done

Using Github actions to build the s3gw results in lengthy build times of more than 2h. It's not efficient.

### Acceptance Criteria

Being able to run builds in either of these solutions.

**Comment by giubacc** [comment]
IMO this item is too much vast and cannot be treated as a single item.
Given that we already have a CI up and running we should focus on the optimization of our current implementation of it.
IMO, a prerequisite that we need to satisfy is to have our infrastructure on the cloud and overcome self-hosted runners.
I'd avoid to spend more time in research activities, the need we have now is clear: move to cloud.

**Comment by jhmarina** [comment]
Yes, I think you're right, we have already established our needs here. I'll close this one.
