### ISSUE TITLE
rgw/sfs: Provide retention information via `headObject` call

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#367]
After https://github.com/aquarist-labs/ceph/pull/111 has implemented the core functionality, the UI want to consume that information via https://github.com/aquarist-labs/s3gw-ui/pull/127.

To get the object meta data the AWS SDK `headObject` call is used. Sadly it looks like this call does not deliver the expected `ObjectLockMode` and `ObjectLockRetainUntilDate` fields.

Alternatively the `getObjectRetention` call could be used, but then the UI has to execute 3 calls to fetch the object meta data that is displayed:

1. headObject to get the core objects meta data
2. getObjectTagging to get the tags
3. getObjectRetention to get the retention settings

References:
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectRetention.html
- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/head_object.html

**Comment by votdev** [comment]
It comes out that the headers [x-amz-object-lock-mode](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax) and [x-amz-object-lock-retain-until-date](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax) headers are send correctly, but the response of the `headObject` function does not reflect that. That need to be investigated.

![Bildschirmfoto vom 2023-03-02 17-33-57](https://user-images.githubusercontent.com/1897962/222547462-9ae7ce8d-0599-416b-a303-42c797e421be.png)

**Comment by votdev** [comment]
I've opened a [bug report](https://github.com/aws/aws-sdk-js/issues/4362) for the AWS SDK.

**Comment by giubacc** [comment]
does it make sense to change tags to `area/upstream` ?

**Comment by jecluis** [comment]
Am I misunderstanding this issue when I assume that there is nothing for us to do in this context? @votdev

**Comment by votdev** [comment]
> Am I misunderstanding this issue when I assume that there is nothing for us to do in this context? @votdev

Correct. I'd implemented a workaround.

**Comment by jecluis** [comment]
So we can safely close this issue? If there is anything to be tracking an upstream issue, I think a dedicated issue would be better.

**Comment by jhmarina** [comment]
@votdev @jecluis should we close this issue then?

**Comment by votdev** [comment]
> @votdev @jecluis should we close this issue then?

As already mentioned, the information can be retrieved by calling another AWS S3 SDK call, but this is more expensive than getting the information with one call.

If s3gw is used in production and external software is using AWS S3 SDK `headObject` function to fetch data, this software might break because s3gw acts unexpected because it does not fully behave like AWS S3.

**Comment by giubacc** [comment]
currently isn't clear to me what is the state of this object, I see a closed upstream issue, is it expected something our side to be done?
@votdev @jecluis

**Comment by jecluis** [comment]
We will reassess whether this is still a problem in an upcoming cycle.

**Comment by jecluis** [comment]
I don't see anything needed to be done here.
