### ISSUE TITLE
footprint reduction: Investigate static link and binary compression

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#37]
This issue comes from the discussion on the mailing list. We want to investigate if static linking & binary compression may help us in reducing the container footprint. Here's an excerpt of the conversation:

> There are some more involved options that we could investigate:
> Static linking and compressing the binary (e.g. with upx). This may impact some performance characteristics like startup time
> Static linking might also allow us to eventually use options like
> -fwhole-program at compile time, and -flto.

> That might help us drop unused functions from the resulting binary without needing massive code/ifdef parties - at least if the compiler can truly determine the functions aren't called.

Depending on the outcome of the investigation, we'll work on the implementation.

**Comment by jecluis** [comment]
this is something we would still like to look into, at some point, time permitting. we should also follow up upstream and see where the rgw team is with carving out rgw from rados.

**Comment by asettle** [comment]
Not going to happen
