### ISSUE TITLE
Set up chart to deploy multiple S3 gateways in a cluster

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#380]
### What needs to be done

Figure out if we can have multiple gateways running with different namespaces (or names) -> consuming different Longhorn volumes. We don't think we can claim the same volume, but it may be worth double-checking.

### Why it needs to be done

Ideally, we'd like to run multiple s3gw targets in the same cluster, although if we opt not to fix this now, this needs to be appropriately documented, since running multiple targets may be possible using different names.

### Acceptance Criteria

- Confirm whether multiple s3gw targets can run in a cluster
- Share findings with the team
- If this is a simple fix, it would be best to fix it, if this is a complex endeavour, document it (discuss it with the team first)

### Additional Information

https://confluence.suse.com/display/RES/2023-03-02+-++s3gw+Strategy+Meeting

**Comment by jecluis** [comment]
@jhmarina maybe I'm being dense, but it's not particularly obvious what the title means. Mind expanding a bit on it?

**Comment by jhmarina** [comment]
@jecluis I added some info to the card, hopefully, it helps. This comes from a discussion we had in the strategy call. The title & content probably need to be improved.

**Comment by m-ildefons** [comment]
The chart is currently not set up to deploy multiple instances in the same cluster as there are cluster wide resources which would create naming conflicts.

**Comment by jhmarina** [comment]
We will in the future, modify the chart to make it deploy multiple times in the same cluster. We'll use this task for the implementation

**Comment by giubacc** [comment]
I think we have fixed this with: https://github.com/aquarist-labs/s3gw/issues/491

**Comment by votdev** [comment]
Fixed by https://github.com/aquarist-labs/s3gw-charts/pull/98.
