### ISSUE TITLE
charts: Dynamic provisioning

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#41]
## What needs to be done

We need Dynamic provisioning. Specify a different StorageClass so can leverage another dynamic provisioning such as Longhorn. 

## Why it needs to be done

The Helm chart UX needs to be improved so it is easier to use.

## Acceptance Criteria

The user is able to reference an existing StorageClass different to Longhorn.

## Additional Information

**Comment by l-mb** [comment]
We already allow specifying a PVC, and for Longhorn we simply define our own storageclass already. Referencing an existing StorageClass should be straightforward.

**Comment by jecluis** [comment]
@m-ildefons do you have an opinion on this?
