### ISSUE TITLE
[BUG] Bucket List: copy to clipboard does not work

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#420]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

```

seri@janelane  ☻  ~/bin
echo "" | xclip -i -selection primary

[2023-03-29T14:36:38Z] echo "" | xclip -i -selection primary

seri@janelane  ☻  ~/bin
echo "" | xclip -i -selection clipboard

[2023-03-29T14:36:41Z] echo "" | xclip -i -selection clipboard

seri@janelane  ☻  ~/bin
xclip -o -verbose -selection primary

[2023-03-29T14:36:52Z] xclip -o -verbose -selection primary

Connected to X server.
Using selection: XA_PRIMARY
Using UTF8_STRING.
Type is UTF8_STRING.

seri@janelane  ☻  ~/bin
xclip -o -verbose -selection clipboard

[2023-03-29T14:36:57Z] xclip -o -verbose -selection clipboard

Connected to X server.
Using selection: XA_CLIPBOARD
Using UTF8_STRING.
Type is UTF8_STRING.
```

Click button "Save to clipboard" on
http://s3gw-ui.fe.10.104.88.44.omg.howdoi.website/#/objects/bucket1

```
seri@janelane  ☻  ~/bin
xclip -o -verbose -selection primary

[2023-03-29T14:37:01Z] xclip -o -verbose -selection primary

Connected to X server.
Using selection: XA_PRIMARY
Using UTF8_STRING.
Type is UTF8_STRING.

seri@janelane  ☻  ~/bin
xclip -o -verbose -selection clipboard

[2023-03-29T14:37:02Z] xclip -o -verbose -selection clipboard

Connected to X server.
Using selection: XA_CLIPBOARD
Using UTF8_STRING.
Type is UTF8_STRING.

```

No change to clipboard or primary selection.
No errors in the browser console

**Desktop (please complete the following information):**

- OS: Tumbleweed X11
- Browser vivaldi (chromium)
- Version 0.14.0-rc1

**Additional context**

**Comment by votdev** [comment]
Can not reproduce that using Chrome Version 111.0.5563.146 and FireFox 111.0.1.

![Peek 2023-03-29 17-13](https://user-images.githubusercontent.com/1897962/228585999-b0ce6f76-4dc5-4f6d-a25b-6c25608fdb14.gif)

**Comment by m-ildefons** [comment]
Can't reproduce with s3gw v0.16.0 either. Path is successfully copied to the clipboard. I'm going to close this, please re-open and add details if it's still a problem.
