### ISSUE TITLE
Send periodic update queries to upgrade responder

### ISSUE THREAD

**Issue by l-mb** [s3gw-tech/s3gw#423]
### What needs to be done

Periodically (as instructed by the upgrade responder endpoint) send updated telemetry and inquire about the most recent version (endpoint: s3gw.version.rancher.io)

### Acceptance Criteria

End-to-end: data shown correctly in Grafana dashboard.

### Additional Information

https://github.com/aquarist-labs/s3gw/issues/202

**Comment by l-mb** [comment]
In addition to the data discussed in the main epic, I'd also recommend to add a `testEnv` boolean so we can filter out our CI/CD submissions from the main data.

**Comment by irq0** [comment]
Periodic updater went in with https://github.com/aquarist-labs/ceph/pull/133.
Follow up issue with list of additional data to send: https://github.com/aquarist-labs/s3gw/issues/443

**Comment by l-mb** [comment]
According the the LH responder docs, we shouldn't hardcode the update interval but comply with what the server tells us in the response (`requestIntervalInMinutes`)?

Once you're done with the issue feel free to close!

**Comment by irq0** [comment]
Tracking the the requestIntervalInMinutes as a bug in  #529
