### ISSUE TITLE
Clean up container registry and image pushes

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#424]
### What needs to be done

Clean and organize quay repo

### Why it needs to be done

It's a mess and getting worse with each nightly build

### Acceptance Criteria

- Set expiry dates on nightly containers
- Separate out buildenv and development containers into a different repo, so it doesn't pollute the quay repo
- Figure out the "ghost layers" in the release containers

**Comment by jhmarina** [comment]
@m-ildefons needs to look into why those "ghost layers" are there. Other than that, the remaining issues have been addressed.

**Comment by jhmarina** [comment]
There is no documentation telling what causes those ghost layers to appear. Since reorganizing the quay repo was done, we'll close this issue and revisit the issue with ghost layers.
