### ISSUE TITLE
Release builds don't have a proper ceph version set

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#431]
**Describe the bug** 

```
[2023-04-05T15:01:27Z] podman run 'quay.io/s3gw/s3gw:v0.14.0' --version

ceph version Development (no_version) reef (dev)
```

This is the default for devel builds without git versioning enabled.
See also ceph_ver.h.in, ceph_ver.h
```
#define CEPH_GIT_VER no_version
#define CEPH_GIT_NICE_VER "Development"
#define CEPH_RELEASE 18
#define CEPH_RELEASE_NAME "reef"
#define CEPH_RELEASE_TYPE "dev"
```

**Expected behavior** 

```
[2023-04-05T15:02:09Z] podman run 'quay.io/s3gw/s3gw:v0.13.0' --version

ceph version s3gw-v0.13.0 (7fa0c195642b49bc2dba00347990685514507882) reef (dev)
```

**Additional context** 

We need the version in the release for the update responder / telemetry / benchmark tools / --version.

https://github.com/aquarist-labs/s3gw/issues/423 depends on the s3gw version available.

**Comment by vmoutoussamy** [comment]
@tserong Could you please check this?

**Comment by tserong** [comment]
Yeah, it's busted for release builds, but works fine for manual builds out of the ceph source tree. I'll see what I can do to fix that.
