### ISSUE TITLE
Add tests that need to be run to a list

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#465]
### What needs to be done

We want to have all the tests to be run in a list or script so that they are added to the container running the tests. 

These tests would then either be executed 1 by 1 or all at once.

**Comment by m-ildefons** [comment]
Currently we determine the unit tests that need to be build and run dynamically. This is a source of unreliability with the potential that unit tests are not run completely or not run at all. This failure is silent as the CI will not fail. Thus it is hard to detect.

The aim is to have single source of truth list of unit tests that we need to build and run. This list can of course be extended, but we can be sure that tests that are on it aren't omitted.

Take inspiration from the s3tests, which are also selectively run from a list.

**Comment by m-ildefons** [comment]
related PR: aquarist-labs/ceph#143
We might also use labeling and ctest instead of a fixed list, but regardless of the actual implementation, this issue will be used to track fixing the unit test discovery to something that doesn't rely on sticking to a naming scheme and regexes.

**Comment by giubacc** [comment]
@m-ildefons isn't there a PR of yours addressing this issue? If so mind link that to this issue (I remember I saw something regarding that few days ago? ) ?
If you are working on this topic or you count to work this in the future would be better to assign this to you.

**Comment by jecluis** [comment]
we have the s3tr now, that should address this issue.
