### ISSUE TITLE
Check and improve versioning s3tests

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#472]
Right now we are running only 7 out of 21 s3 tests for versioning, because the rest are either failing or not checked for a long time.

It would be good to have a better s3 tests versioning coverage, which would mean that we are following the S3 standard for that particular area. 

This is the list of tests not being executed

- test_bucket_list_return_data_versioning
- test_object_copy_versioning_multipart_upload
- test_versioning_obj_create_read_remove
- test_versioning_obj_create_read_remove_head
- test_versioning_obj_plain_null_version_overwrite
- test_versioning_obj_suspend_versions
- test_versioning_obj_create_versions_remove_all
- test_versioning_obj_create_versions_remove_special_names
- test_versioning_obj_create_overwrite_multipart
- test_versioning_obj_list_marker
- test_versioning_copy_obj_version
- test_versioning_multi_object_delete
- test_versioning_multi_object_delete_with_maker

**Comment by irq0** [comment]
Also interesting:

test_versioned_concurrent_object_create_and_remove	fail
test_versioned_concurrent_object_create_concurrent_remove	fail

They test list versions

**Comment by 0xavi0** [comment]
Implementing as in https://github.com/aquarist-labs/s3gw/pull/497
