### ISSUE TITLE
Reconcile possible duplicated columns in object and versioned object tables

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#480]
Right now there are a few columns in `objects` and `versioned objects` tables in `sqlite` that are repeated or describe the same thing.

We should decide which table holds those columns. 

Columns we can discuss about: 

* size
* etag
* creation_time
* mtime
* set_mtime
* detele_at_time

**Comment by irq0** [comment]
https://github.com/aquarist-labs/s3gw/pull/497, design review 2023-05-05 concluded that we use the versioned object for metadata. Changes:

```
           sqlite_orm::make_column("bucket_id", &DBObject::bucket_id),
           sqlite_orm::make_column("name", &DBObject::name),
-          sqlite_orm::make_column("size", &DBObject::size),
-          sqlite_orm::make_column("etag", &DBObject::etag),
-          sqlite_orm::make_column("mtime", &DBObject::mtime),
-          sqlite_orm::make_column("set_mtime", &DBObject::set_mtime),
-          sqlite_orm::make_column("delete_at_time", &DBObject::delete_at_time),
```
