### ISSUE TITLE
rgw/sfs: Add Garbage collector processor period 

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#483]
Right now GC supports the `--rgw_gc_max_objs` parameter.

It would, maybe, be interesting to add `rgw_gc_processor_period` to be able to fine tune the time GC is allowed to work per execution cycle.

**Comment by giubacc** [comment]
@0xavi0 could this be integrated into the current work allocated for the GC?

**Comment by 0xavi0** [comment]
I think it will... from a team chat I think we talked about time GC based on time rather than max objects, because max_objects was more something related to `rados`

**Comment by jhmarina** [comment]
@giubacc @0xavi0 I've added the issue to the GC epic

**Comment by 0xavi0** [comment]
This was implemented in https://github.com/aquarist-labs/ceph/pull/165
