### ISSUE TITLE
charts: allow custom storage class provisioner

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#492]
When the helm chart creates the storage class, the user should be allowed to specify a custom provisioner.
Currently, this is hardcoded to:  `driver.longhorn.io`

**Comment by giubacc** [comment]
@m-ildefons we currently choose to be opinionated regarding the storage class provisioner.
Are there motivations we should be pro or con to this decision?

**Comment by m-ildefons** [comment]
Longhorn is our current target platform for storage. We allow other storage classes already and that means other storage providers too. Unless you have a specific provider in mind, I don't see us supporting others directly.

**Comment by giubacc** [comment]
Probably I opened this issue when we were defaulting to LH storageclass.
I think we can close this.
