### ISSUE TITLE
Create a compatibility matrix

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#515]
*x* must know what is working and to what extent.

case *x* in
 - *s3gw developers*: Where to focus work? Avoid blind spots.
 - *users*: Does s3gw fit the use case? Set expectations.

Example:
https://docs.ceph.com/en/latest/radosgw/s3/#features-support

The report should be data driven and automated. S3 operations like GET object have nuance (e.g If-matched, If-Unmodified-Since)  and we should show test results to back our claims. 

Minimum we should have this per release. 
Better: release + nightly. 
Awesome: per PR reports that compare results to known failing (== WIP) tests and comment if there is a difference between them. This could either mean the PR adds support or introduces a regression.

To get data we can largely leverage https://github.com/ceph/s3-tests.

Unfortunately s3-tests aren't tagged or grouped strictly around S3 features. We would need to categorize tests in order to condense them into S3 support categories (e.g 'Bucket List'). 

#### Categories

As a starting point, some categories.

```
* Bucket
** List
** Delete
** Create
** Lifecycle
** Replication
** Policies
** Website
** ACLs
** Location
** Notification
** Versioning
Unversioned, versioned, versions suspended buckets
** Get Bucket Info (HEAD request)
** Tagging
* Object
** Put
** Delete
** Get
** ACLs
** POST
** Copy
** Multipart Uploads
** Tagging
** Storage Classes
```

#### Possible Implementation around Datasette

- Start with the test results in SQLite from s3-tests runs (See https://github.com/aquarist-labs/s3gw/pull/528).
- Create SQL queries for each category. Get the success ratio, list of test failing, ideally attach severity and github issues.
- Create Datasette dashboard. Include pie chart of overall success/fail. Compatibility score. Compatibility per group. etc.
- Publish Datasette somewhere. Add to CI pipeline.

Additional benefit of the Datasette approach: Searchable (full text :heart:)  results (logs, test output) for developers. 

https://datasette.io is an SQLite based data analysis tool

**Comment by l-mb** [comment]
I'd like to suggest that being able to advise users which S3 API calls/features work is mandatory for GA, both for the evaluation and limiting the support matrix scope.

**Comment by jecluis** [comment]
@l-mb do you think this is addressed by the current matrix available in the docs?
