### ISSUE TITLE
UI: Setup core E2E framework

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#520]
Setup the core E2E framework for the Angular based UI.

**Comment by jhmarina** [comment]
Closing this issue as the work on e2e testing will be tracked by the Epic: https://github.com/aquarist-labs/s3gw/issues/292

**Comment by Ameenasuhani** [comment]
Currently, implementation of s3gwi-ui testing has been done using Cypress for this issue
The addition of the below test is done
- **log in** ,  **top bar and dashboard  page view** and **visibility**
- bucket management ( bucket create, delete, edit, list)
- user management(user create, delete, list)
as mentioned by @jhmarina the work on e2e testing will be tracked by the Epic: https://github.com/aquarist-labs/s3gw/issues/292
