### ISSUE TITLE
Longhorn UI support and integration (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#541]
### What needs to be done
Implement s3gw UI integration into Longhorn:
- Enable users to request on-demand object storage instances
  - Enhance Longhorn Volume Creation page for creating S3 endpoints
- Display capacity utilization for storage insights
- **Note**: Consider Longhorn team's plan to rewrite UI in the 1.6 release. Collaborate closely for seamless integration.

### Acceptance Criteria

1. The s3gw UI is successfully integrated into the Longhorn user interface, ensuring a seamless user experience..
1. Users can request on-demand object storage instances through the enhanced Longhorn Volume Creation page.
1. The Longhorn UI is updated to display accurate capacity utilization for storage insights.
1. Close collaboration with the Longhorn team to ensure seamless integration, considering their plan to rewrite the UI in the 1.7 release (maybe).

### Additional Information
https://confluence.suse.com/display/RES/Longhorn-s3gw+Integration+Plan#Longhorns3gwIntegrationPlan-%22Experimental%22Schedule

### My tasks
- [ ] https://github.com/longhorn/longhorn-ui/pull/614
- [ ] #512
- [ ] https://github.com/aquarist-labs/longhorn-ui/pull/1

**Comment by vmoutoussamy** [comment]
Should be closed when https://github.com/aquarist-labs/longhorn-ui/pull/1 is merged.

**Comment by jecluis** [comment]
Appeasing our LH overlords is no longer part of the plan.
