### ISSUE TITLE
Object storage management (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#542]
### What needs to be done
Implement object storage management in Longhorn:

- Utilize Longhorn's helm charts for delivery in the longhorn-system namespace.
- Manage object storage endpoints dynamically during runtime, contrasting with Longhorn RWX volume management handled during installation.
- Guarantee in-cluster endpoint access for seamless functionality.

### Acceptance Criteria
These are still to be defined.

### Additional Information
https://confluence.suse.com/display/RES/Longhorn-s3gw+Integration+Plan#Longhorns3gwIntegrationPlan-%22Experimental%22Schedule

```[tasklist]
### My tasks

```

**Comment by jecluis** [comment]
No longer focusing on anything LH
