### ISSUE TITLE
Object Storage backup and restore (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#543]
### What needs to be done
Implement object backup and restore functionality:

- Enable users to back up object storage at the volume or bucket level.
- Implement a regular backup scheduler to automate backup processes and provide visibility into backups.
- Allow users to delete backups and restore object storage from the available backups.

### Acceptance Criteria
These are still to be defined.

### Additional Information
https://confluence.suse.com/display/RES/Longhorn-s3gw+Integration+Plan#Longhorns3gwIntegrationPlan-%22Experimental%22Schedule

```[tasklist]
### My tasks
```

**Comment by jecluis** [comment]
This particular issue is focused on LH integration, which we're no longer doing.
