### ISSUE TITLE
UI: Edit bucket in UI allows user to switch retention mode

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#553]
**Describe the bug** A clear and concise description of what the bug is.
When a bucket is created with UI using bucket create a form with object lock and retention enabled on it. The bucket edit allows the user to switch between Compliance and Governance retention mode and also allows the user to modify the retention period in Compliance mode

**To Reproduce** Steps to reproduce the behavior:

1. go to bucket create form and create a bucket with governance or compliance retention mode
2. from the bucket list page click on the edit button, and the user allowed to switch between Compliance and Governance retention mode
[Screencast from 2023-06-01 21-56-02.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/1047e72d-9150-4559-879b-59a0e25a3e56)

**Expected behavior** A clear and concise description of what you expected to
happen.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html#object-lock-retention-modes

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by jhmarina** [comment]
@jhmarina sill split this issue into two: UI & RGW/SFS
