### ISSUE TITLE
UI: Unable to create customized access key and secret key for a user

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#558]
**Describe the bug** A clear and concise description of what the bug is.
Unable to create customized access key and secret key for a user

**To Reproduce** Steps to reproduce the behavior:

1. Go to the users page with administration enable
2.  click on Manage Keys 
3. Click on Create button to create user keys
4. Disable autogenerated key and add 16 digit user and secret key
5. Click on Create button, it shows failed to save data and log out of the UI
6.  Also  follow step-1 to step-4 again and click on the Cancel button it still logs the user out

**Expected behavior** A clear and concise description of what you expected to
happen.
The user should be able to access UI with customized access and secret key

**Screenshots** If applicable, add screenshots to help explain your problem.
[Screencast from 2023-06-05 12-20-45.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/e1c29c63-924e-4051-8c28-17f86900e206)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by jhmarina** [comment]
@jhmarina will create an Epic for this.

**Comment by votdev** [comment]
Can not reproduce that issue anymore with v0.21.0-rc1.

![Peek 2023-09-27 11-04](https://github.com/aquarist-labs/s3gw/assets/1897962/542dd647-b84a-4eb3-9132-42f46afa4a2f)
