### ISSUE TITLE
UI: The Show/Hide button must have at least one default value

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#560]
**Is your feature request related to a problem? Please describe.** 
It is **good to have** the Show/Hide button with at least one default value on the bucket and user list page.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.
One default value that is not listed under Show/Hide button

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.
![Screenshot from 2023-06-06 14-54-59](https://github.com/aquarist-labs/s3gw/assets/40173964/2747dcac-5114-4615-b1b3-1828280c0130)
![Screenshot from 2023-06-06 14-56-52](https://github.com/aquarist-labs/s3gw/assets/40173964/543a5f90-efff-4fc1-a3a1-4faf6ca10e03)

**Comment by votdev** [comment]
Nice to have, but IMO the user is responsible for what he is doing. If the user deactivates all columns, he should not be surprised that no columns are displayed in the table.

**Comment by jhmarina** [comment]
Not having all columns disabled is a standard UX pattern, we should aim at ensuring this is the case
