### ISSUE TITLE
Evaluate if it makes still sense to keep `configmap.yaml`

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#561]

**Comment by l-mb** [comment]
@jhmarina Do you remember why we needed to evaluate this? Thanks!

**Comment by jhmarina** [comment]
@l-mb I'm not sure why we wanted to evaluate it. There should have been more information on this card, my bad! 

I've searched through the meeting minutes and all I could find is [this](https://confluence.suse.com/display/RES/2023-04-11+-++Q2+items+Xavi), which isn't very helpful either, I'm afraid!
