### ISSUE TITLE
rgw/sfs: Edit bucket in UI allows user to switch retention mode

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#566]
**Describe the bug** A clear and concise description of what the bug is.
When a bucket is created with UI using bucket create a form with object lock and retention enabled on it. The bucket edit allows the user to switch between Compliance and Governance retention mode and also allows the user to modify the retention period in Compliance mode

**To Reproduce** Steps to reproduce the behavior:

1. go to bucket create form and create a bucket with governance or compliance retention mode
2. from the bucket list page click on the edit button, and the user allowed to switch between Compliance and Governance retention mode
[Screencast from 2023-06-01 21-56-02.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/1047e72d-9150-4559-879b-59a0e25a3e56)

**Expected behavior** A clear and concise description of what you expected to
happen.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html#object-lock-retention-modes

## Notes
There's a corresponding bug filed for the UI: https://github.com/aquarist-labs/s3gw/issues/553

**Comment by giubacc** [comment]
I think there was a miscomprehension somewhere at the time this was opened.
You are allowed to change the default retention mode **at any time** for any object-lock enabled bucket.
You can change it from/to compliance/governance without any restriction.
The point is that the default retention applies for all the new objects created from that time-point on.
It does not affect existing object that retain their existing retention setting.
So it is completely fine change the default retention for a bucket at any time.
Now, `0.21.0`,  the ui is preventing you certain operations depending on the current state of the bucket, but this is wrong.
Eg: we are blocking going to Compliance -> Governance, but it should actually pass.
Different thing if you are doing this over an object, that is correct not being able to change to Compliance -> Governance.

If you look at the [PutObjectLockConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLockConfiguration.html) API, there is no mention about restrictions for this call.

[Retention modes rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html#object-lock-retention-modes) apply to objects, not on bucket's default retention modes.

FYI @Ameenasuhani @votdev

**Comment by giubacc** [comment]
closing as invalid
