### ISSUE TITLE
Fix Logo on artifacthub.io

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#570]
Fix the logo. 

Fix this by providing the correct URL in the charts repo and uploading a high-resolution PNG version of the logo somewhere safe*

*safe from getting moved/renamed

**Comment by jhmarina** [comment]
The logo should be uploaded here: https://github.com/aquarist-labs/s3gw-website and then the https://github.com/aquarist-labs/aquarium-website repo should be archived again

**Comment by jhmarina** [comment]
Rancher app catalog may also be using that logo
