### ISSUE TITLE
UI: Simplify the deletion process by implementing a single delete button for bucket/user

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#575]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

We can have a single button to delete the bucket/user instead of having multiple delete buttons just to improve the user experience.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.
![Screenshot from 2023-06-09 12-27-09](https://github.com/aquarist-labs/s3gw/assets/40173964/5761e3ec-df3a-4239-9049-63691da2cf44)

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by votdev** [comment]
The current implementation is aligned to the Rancher user interface. There are also double buttons for various actions.

![Bildschirmfoto vom 2023-06-12 09-14-44](https://github.com/aquarist-labs/s3gw/assets/1897962/34280ac7-2f74-4714-972a-ed96e5258947)

**Comment by Ameenasuhani** [comment]
It makes sense to close this issue as the UI is adapted to the Rancher UI.
