### ISSUE TITLE
[UI] Lifecycle rule create is not working using UI

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#587]
**Describe the bug** A clear and concise description of what the bug is.
Lifecycle rule creation is not working using UI

**To Reproduce** Steps to reproduce the behavior:

1. Go to s3gw-ui
2. Create a bucket and create the lifecycle rule

**Expected behavior** A clear and concise description of what you expected to
happen.
The lifecycle rule should be created

**Screenshots** If applicable, add screenshots to help explain your problem.
[Screencast from 2023-06-14 19-34-22.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/7c0e46b9-4d78-4d8d-ac03-a005d71fcb1c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by votdev** [comment]
```
ERROR MissingRequiredParameter: Missing required key 'Status' in params.LifecycleConfiguration.Rules[0]
```
Seems there were some changes to the API since the feature has been implemented.

**Comment by votdev** [comment]
A workaround is to create a disabled rule and then enable it after creation.
