### ISSUE TITLE
When object lock is enabled the object shouldn't be deleted

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#590]
**Describe the bug** A clear and concise description of what the bug is.
With object lock enabled the object is deleted. When all versions are selected to be deleted error is thrown but when the current version is deleted the object is deleted.

**To Reproduce** Steps to reproduce the behavior:

1. Go to UI and create a bucket with object lock enabled 
2. Add multiple versions of objects
3. Delete the current version of the object

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.
[Screencast from 2023-06-16 12-43-22.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/93bf1662-133a-4bd0-8eb7-74efca5baa8d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by jhmarina** [comment]
This issue may be related to https://github.com/aquarist-labs/s3gw/issues/419 and needs further investigation. I may not just be a UI issue but also a Backend issue.

**Comment by votdev** [comment]
This behaviour is expected.

With object locking and retention enabled the following is possible:

- Delete the latest version => a delete marker is created. The previous version can be restored.
- Deleting ALL version is forbidden.
