### ISSUE TITLE
chart: default email value for s3gw-letsencrypt-issuer clusterIssuer is forbidden by LE

### ISSUE THREAD

**Issue by thehejik** [s3gw-tech/s3gw#596]
**Describe the bug**
When s3gw is installed with default values over helm (without requesting LE certificate for its domain) the clusterIssuer `*-s3gw-letsencrypt-issuer` is in `Unavailable` state.

**To Reproduce** Steps to reproduce the behavior:
Install with default values:
```
helm upgrade --install s3gw s3gw/s3gw --namespace s3gw \
    --create-namespace --set ingress.enabled=true \
    --set publicDomain=domain --set ui.publicDomain=domain
```
Check output of:
```
$ kubectl get clusterIssuer -lapp.kubernetes.io/name=s3gw        
NAME                           READY   AGE
s3gw-s3gw-self-signed-issuer   True    2m38s
s3gw-s3gw-letsencrypt-issuer   False   2m38s
s3gw-s3gw-issuer               True    2m38s
```

See details of the Failed clusterIssuer:
```
$ kubectl get clusterIssuer s3gw-s3gw-letsencrypt-issuer -o yaml
...
spec:
  acme:
    email: mail@example.com
 ...
status:
  acme: {}
  conditions:
  - lastTransitionTime: "2023-06-23T07:38:51Z"
    message: 'Failed to register ACME account: 400 urn:ietf:params:acme:error:invalidContact:
      Error creating new account :: invalid contact domain. Contact emails @example.com
      are forbidden'
    observedGeneration: 1
    reason: ErrRegisterACMEAccount
    status: "False"
    type: Ready
```

**Expected behavior**
All the resources should be in Ready state.
Maybe a different email than `mail@example.com` should be used here https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/values.yaml#L17

**Comment by giubacc** [comment]
@m-ildefons I don't remember if we explicitly decided to put an `example.com` email to make the failure explicit and force the user to put a value here.
We can decide to change this if we think we should.

**Comment by m-ildefons** [comment]
I think I put it there, expecting anyone who is actually using it to recognize it as placeholder and change it. Clearly that was wrong and we should build a function similar to the ones used for (ui.)publicDomain that fails the templating if it detects that the user didn't input an acceptable value.
I still believe the default should remain at `example.com`, since it's impossible to give a default value that would be accepted by letsencrypt.
