### ISSUE TITLE
[BUG] Security report from Rancher image scanning - HIGH severity issues in curl dependencies.

### ISSUE THREAD

**Issue by andreas-kupries** [s3gw-tech/s3gw#597]
Reference: https://github.com/rancherlabs/image-scanning/issues/2309
Local copy of the description:

Vulnerability ID | Title | Package Name | Fixed Version | Severity | Target
-- | -- | -- | -- | -- | --
SUSE-SU-2023:2224-1 | Security update for curl | curl | 8.0.1-150400.5.23.1 | HIGH | rancher/mirrored-s3gw-s3gw:v0.14.0 (opensuse.leap 15.4)
SUSE-SU-2023:2224-1 | Security update for curl | libcurl4 | 8.0.1-150400.5.23.1 | HIGH | rancher/mirrored-s3gw-s3gw:v0.14.0 (opensuse.leap 15.4)

This issue is for s3gw 0.14.0.

**Comment by jecluis** [comment]
I think the path here is to check whether we are still affected by this vulnerability in current versions, and address it if so in the next release.

Lets keep in mind we are still in a pre-beta stage, and devoting time and resources to address a `curl` issue (which is not a dependency of our executables themselves), to release a patch version, is maybe a bit overkill

And I'd suggest marking this as a "won't fix" for v0.14.0.

**Comment by jecluis** [comment]
Also, thank you @andreas-kupries for the report. Very much appreciated! :)

**Comment by jhmarina** [comment]
This has been fixed with the latest version of s3gw. I'm closing this issue as we won't address the issue for v0.14 since we're in a pre-beta stage, as mentioned.
