### ISSUE TITLE
UI/Backend: Add auth endpoints

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#608]
We need to have endpoints for authentication. I suggest `/auth` ans prefix.

The really necessary endpoints are:

- `/auth/login`
- `/auth/logout`

The existing [Typescript](https://github.com/aquarist-labs/s3gw-ui/blob/main/src/frontend/src/app/shared/services/api/auth.service.ts) implementation can be used as template.

Maybe we should use JWT for this, but this may require additional tools to manage the tokens (revoke, delete, ...). Maybe it is better to keep the existing auth management in the frontend and do not do any auth management in the backend. The Admin Ops and S3 API reject requests at the latest when the access and secret keys are invalid.

**Comment by giubacc** [comment]
I agree that this logic should be kept on UI-frontend.
UI-Backend should only be a "stateless" layer: the responsibility to eventually keep the pair: access_key/secret_key inside a store should be of the frontend UI.
UI-Backend should be kept as a true restful layer.

**Comment by votdev** [comment]
At the present time (v0.21.0) the access and secret key of the user are used as login credentials. The [authenticate](https://github.com/aquarist-labs/s3gw-ui/blob/main/src/backend/api/auth.py#L36) endpoint checks if the credentials are valid. If successful, the UI gets notified. From this point all API calls contain the credentials in the `s3gw-credentials` header, so that the REST API is stateless in that regards.
