### ISSUE TITLE
[Backlog] Restructure documentation to reflect Rancher doc standards

### ISSUE THREAD

**Issue by asettle** [s3gw-tech/s3gw#628]
### What needs to be done

Rancher projects are standardising their documentation efforts and the s3gw has been invited to do the same thing.

### Why it needs to be done

The s3gw is integrating with Longhorn. To provide a seamless experience for all Rancher projects and products, we should align our documentation to reflect the style used by the wider organisation. 

### Acceptance Criteria

- [ ] Update documentation site to use docusaurus: https://docusaurus.io/ 
- [ ] Update GitHub actions for publishing the docs. Example: RKE2 docs repo - https://github.com/rancher/rke2-docs)
- [ ] Standardise docs URL to `docs.<projectname>.io`
- [ ] Restructure documentation layout Example: [Rancher Desktop docs](https://docs.rancherdesktop.io/getting-started/installation/).

**Comment by jecluis** [comment]
we no longer need to meet rancher standards
