### ISSUE TITLE
rgw/sfs: Data information is not displayed when the object details are expanded

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#632]
**Describe the bug** A clear and concise description of what the bug is.
 Data information is not displayed when the object details are expanded for an unversioned bucket

**To Reproduce** Steps to reproduce the behavior:

1. Go to UI
2. Create a bucket without versioning and object locking. The size is displayed in the column but when we expand the object details it is null and the content type is also null

**Expected behavior** A clear and concise description of what you expected to
happen.
The size and content type should be displayed upon expanding object details

**Screenshots** If applicable, add screenshots to help explain your problem.
[Screencast from 2023-07-24 12-31-56.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/8827813b-7cca-4a52-8290-ddf961e1d348)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by votdev** [comment]
This is a regression. With the `v0.17.0` s3gw container it is possible to execute a `headObject` with `versionID` = `"null"`. With `v0.18.0` this is not possible anymore.

![Peek 2023-07-25 15-02](https://github.com/aquarist-labs/s3gw/assets/1897962/79899f4d-c28b-4636-b277-8eb37e58b9cc)

**Comment by votdev** [comment]
The issue is not reproducible with a custom build container using the latest [s3gw code](https://github.com/aquarist-labs/ceph/tree/s3gw). It seems it has been fixed in the meanwhile since `v0.18.0`.

**Comment by Ameenasuhani** [comment]
@votdev Thanks!
The issue is not reproducible with the latest version of the s3gw container and UI looks like it was a mismatch
