### ISSUE TITLE
[UI]:  Remove the scroll option from the data table head

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#633]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]
Remove the scroll option from the data table head

**Describe the solution you'd like** A clear and concise description of what you
want to happen.
Since text break is not applicable for most of the data table head remove the scroll option

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.
![Screenshot from 2023-07-24 13-10-44](https://github.com/aquarist-labs/s3gw/assets/40173964/fc9a3616-a92a-409d-b264-09283a46d0fd)

**Comment by votdev** [comment]
I was not able to reproduce the issue, but added a CSS class that prevents showing the scrollbars.
