### ISSUE TITLE
[UI]: The checkbox for enabling administration does not work as intended

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#650]
**Describe the bug** A clear and concise description of what the bug is.
 The checkbox for enabling administration does not work as intended

**To Reproduce** Steps to reproduce the behavior:

1. Go to UI
2. Enable administration and create a user and enable administration on a new user

**Expected behavior** A clear and concise description of what you expected to
happen.
The administration should be enabled

**Screenshots** If applicable, add screenshots to help explain your problem.
[Screencast from 2023-08-02 12-55-43.webm](https://github.com/aquarist-labs/s3gw/assets/40173964/084e77f0-c778-4b9b-9e55-c2a27f7bc5ba)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Browser [e.g. stock browser, safari]: Chrome Version 112.0.5615.165 (Official Build) (64-bit)

**Additional context** Add any other context about the problem here.

**Comment by votdev** [comment]
This feature is based on https://github.com/aquarist-labs/ceph/pull/166 which requires a `v0.19.0` s3gw container. Are you using this version or are you testing it with a `v0.18.0` container?

**Comment by Ameenasuhani** [comment]
@votdev Thanks!
The issue is not reproducible with the latest version of the s3gw container and UI looks like it was a mismatch
