### ISSUE TITLE
[BUG] [UI] Can not upload certain files

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#653]
**Describe the bug** A clear and concise description of what the bug is.

During uploading of _some_ files, but not all, an error happens in the UI that causes the upload to fail

**To Reproduce** Steps to reproduce the behavior:

1. Create a Bucket from the UI and open the bucket explorer
2. Upload various files, e.g. an mp4 file

**Expected behavior** A clear and concise description of what you expected to
happen.

A user should be able to upload any file they wish

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/aquarist-labs/s3gw/assets/17141774/a1348c02-3271-4f71-99d8-0fad5471a3a5

**Comment by m-ildefons** [comment]
This seems to affect files over 1MiB in size

**Comment by votdev** [comment]
Can not reproduce that with a 96MiB file.
![Peek 2023-08-03 13-52](https://github.com/aquarist-labs/s3gw/assets/1897962/f47d8125-bd39-4b38-8a3b-0f2fed0fb0eb)
I'm running a v0.19.0 GW, but this container is a little bit older. So maybe some latest s3gw changes may cause the issue.

**Comment by votdev** [comment]
@m-ildefons Can you please post the response of the failing API request (by using the browser dev tools)?

**Comment by m-ildefons** [comment]
There you go.
https://github.com/aquarist-labs/s3gw/assets/17141774/405a1e8e-54b4-40e1-aad6-704c57f53d1e
I'm running the latest ui build (v0.19.0-rc3) against v0.19.0-rc3 s3gw as well.
I'm using docker-compose with the docker-compose.yaml file from the s3gw repo to run it.
I've also successfully uploaded larger files in the past. The error message indicates to me that something in the HTML DOM generation goes wrong

**Comment by m-ildefons** [comment]
https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size
I think you can close this one as PEBKAC.

To alleviate the CORS issue, in docker-compose, we utilize an nginx reverse proxy. This has a default maximum request body size of 1MiB, but the UI starts splitting files into multiparts only when they are larger than 5MiB (and each part then is up to 5MiB in size). Therefore the nginx proxy answers with a 413 response to the upload request.

I still think the UI here has a bug, because it handles that error poorly. However when I configure nginx to accept uploads larger than 1MiB, the error changes. I think that one should also be a configuration issue rather than an actual bug.

https://github.com/aquarist-labs/s3gw/assets/17141774/b160bd43-f5b1-41b2-90e7-0f9310b058a7

**Comment by jhmarina** [comment]
After double checking with @votdev we're closing this issue

**Comment by m-ildefons** [comment]
Yes. This was a configuration bug with the reverse proxy in my test setup. The linked PR fixes that and this issue will automatically close as resolved when it is merged.
