### ISSUE TITLE
[BUG]: s3gw container crashes  when multiple delete operations are performed

### ISSUE THREAD

**Issue by Ameenasuhani** [s3gw-tech/s3gw#656]
**Describe the bug** A clear and concise description of what the bug is.
s3gw container crashes when multiple delete operations are performed

**To Reproduce** Steps to reproduce the behavior:

1. Go to UI
2. Create  and delete buckets multiple times
3. The container crashes and UI fails to load the data 

**Expected behavior** A clear and concise description of what you expected to
happen.
The container should not crash

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari]: Chrome Version 112.0.5615.165

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.
[crash.log](https://github.com/aquarist-labs/s3gw/files/12272304/crash.log)

**Comment by tserong** [comment]
Here's the relevant assertion failure from the crash log:

```
../src/rgw/driver/sfs/sqlite/sqlite_multipart.cc: In function 'int rgw::sal::sfs::sqlite::SQLiteMultipart::abort_multiparts(const std::string&) const' thread 7f4ba5a99700 time 2023-08-04T12:20:54.684374+0000
../src/rgw/driver/sfs/sqlite/sqlite_multipart.cc: 120: FAILED ceph_assert(bucket_ids_vec.size() == 1)
```

Source is https://github.com/aquarist-labs/ceph/blob/49eea5c18d5f526e2c27637d42a232723e0041fc/src/rgw/driver/sfs/sqlite/sqlite_multipart.cc#L120

It's trying to cleanup multipart uploads associated with the bucket being deleted, and expects there to be only one bucket in the buckets table whose name is equal to the bucket name passed in. Unfortunately, if you create and delete the same bucket twice, you end up with multiple entries in that table, one of them already flagged deleted, e.g.:

```
sqlite> select bucket_id, bucket_name, deleted from buckets;
foo.169138532924741997|foo|1
foo.1691385355482289600|foo|0
```

In this case, `bucket_ids_vec.size()` will be returning 2, hence the assertion failure.

**Comment by jecluis** [comment]
> It's trying to cleanup multipart uploads associated with the bucket being deleted, and expects there to be only one bucket in the buckets table whose name is equal to the bucket name passed in. Unfortunately, if you create and delete the same bucket twice, you end up with multiple entries in that table, one of them already flagged deleted, e.g.:

Oh. That's silly. _sigh_

I'll take care of this.
