### ISSUE TITLE
File layout change: MP parts to subdir; file extensions

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#668]
During the devs meeting file layout came up.

Situation:

object versions (even unversioned object are a version):
`82/8f/eb2b-76c3-48d0-84db-ae655c239901/303`
-> `$object uuid/$global_version_id`

multipart:
`c8/5e/fffa-3f8d-4a02-96e7-d975133927c7-2`
`c8/5e/fffa-3f8d-4a02-96e7-d975133927c7-1`
-> `$multipart_id-$partnum`

Improvements:

1. replace the - in the MPs with a /. parts get their own directory. the filesystem would like it. only one dentry / multipart in `$multipart_id` path. we contain dentry fsync() per part. MPs are temporary, less thrashing of the hash directory to `$multipart_id` (one instead of 10s entries)
2. Add a file extensions. Nice for humans debugging things. Example: MP parts '.p' and versions '.v'.
3. (ongoing discussion) instead of $multipart uuid/$multipart_parts.part_num use $multipart uuid/$multiparts_parts.id

**Comment by tserong** [comment]
> Add a file extensions. Nice for humans debugging things. Example: MP parts '.p' and versions '.v'.

Nice for implementing fsck.s3gw too, which needs to be able to check for orphaned objects. Knowing file types enables us to easily work backwards from a file to check the relevant table in the database to see if a reference to it exists.
