### ISSUE TITLE
Understand and manage SQLite WAL growth

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#681]
We use SQLite in WAL mode. To not overflow the filesystem or degrade performance we must ensure that the WAL doesn't grow to infinity. 

First step is to measure WAL size during various benchmarks.

**Comment by jecluis** [comment]
Related to aquarist-labs/ceph#209

**Comment by irq0** [comment]
Before https://github.com/aquarist-labs/ceph/pull/213 during benchmarks:



![Image](https://github.com/aquarist-labs/s3gw/assets/830867/1a610109-0afb-4ec3-8fee-be1e65a96eb3)

![Image](https://github.com/aquarist-labs/s3gw/assets/830867/30cc7889-bc5a-433e-8f15-8efd432b1549)


Metadata heavy benchmarks, creating lots of small objects caused WAL size explosion. 


After https://github.com/aquarist-labs/ceph/pull/213, we no longer see that.

![Image](https://github.com/aquarist-labs/s3gw/assets/830867/dcfef453-2158-4ad5-bb20-7baef4ffeb91)
