### ISSUE TITLE
[LH] use existing labeling mechanism in object store controller

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#711]
cc @m-ildefons This comment has not been fixed in the latest commit. 

_Originally posted by @PhanLe1010 in https://github.com/longhorn/longhorn-manager/pull/2136#discussion_r1323659354_

**Comment by jecluis** [comment]
Moving all controller stuff to v0.23.0.

@m-ildefons if this is not to be addressed by the initial version of the controller, feel free to push it to a later milestone.

**Comment by jecluis** [comment]
LH related items are no longer part of our plan.
