### ISSUE TITLE
[LH] Add `omitempty` for objectstore.status.state

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#712]
ping @m-ildefons 

_Originally posted by @PhanLe1010 in https://github.com/longhorn/longhorn-manager/pull/2136#discussion_r1323672297_

**Comment by jecluis** [comment]
Moving all controller stuff to v0.23.0.

@m-ildefons if this is not to be addressed by the initial version of the controller, feel free to push it to a later milestone.

**Comment by jecluis** [comment]
LH related work is no longer part of our plan.
