### ISSUE TITLE
Website: The website should mention the UI part of s3gw

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#714]
The https://s3gw.io website should mention the UI part of the project. The UI simplifies the configuration and maintenance of the object store. Sometimes decisions regarding the use of software are made based on the user interface that the software provides. Not mentioning this on the project page could be a disadvantage in this regard.

**Comment by vmoutoussamy** [comment]
@votdev very good idea! We need to fix this! I say let's start small and here are my suggestion:
- We need a 4th reasons why to use s3gw: title "Simplify configuration and maintenance", paragraph: at least 2 sentences.
- We need to show at least 2 screenshots.

@votdev could you please propose something before end of this week? So then we could review it and push it live next week or even earlier?
Thanks
