### ISSUE TITLE
s3gw unit tests show hundreds of "[SQLITE] (21) misuse" errors

### ISSUE THREAD

**Issue by tserong** [s3gw-tech/s3gw#723]
Seen running unit tests in a recent PR (https://github.com/aquarist-labs/ceph/pull/219). I've attached a copy of the results from https://github.com/aquarist-labs/ceph/actions/runs/6296251119/job/17092128691?pr=219. Note the three hundred and ninety seven instances of "[SQLITE] (21) misuse". Weirdly, I don't see these errors when running the unit test binaries I build locally.

[8_Run Unittests.txt](https://github.com/aquarist-labs/s3gw/files/12714500/8_Run.Unittests.txt)

**Comment by tserong** [comment]
I've just checked the results of an earlier PR, from before I added the extra logging to the unit tests (https://github.com/aquarist-labs/ceph/pull/218) which shows only one hundred and seven instances of "[SQLITE] (21) misuse":
[8_Run Unittests.txt](https://github.com/aquarist-labs/s3gw/files/12714745/8_Run.Unittests.txt). So there's always been an issue, it was just slightly less obvious before.

**Comment by tserong** [comment]
> Weirdly, I don't see these errors when running the unit test binaries I build locally.

Ah! But I _do_ see them when I run the tests containerized locally (`docker run --rm s3gw-unittests:latest`)..

**Comment by tserong** [comment]
OK, so the container (built on leap 15.4 using libsqlite3-0-3.39.3) shows the "[SQLITE] (21) misuse" errors. My desktop system is tumbleweed with libsqlite3-0-3.42.0. Sure enough, if I upgrade libsqlite3-0 from 3.93.3 to 3.42.0 _inside_ the container, the errors go away.

**Comment by tserong** [comment]
Found it. We're calling `sqlite3_config(SQLITE_CONFIG_LOG, &sqlite_error_callback, cct);` in `DBConn::DBConn()`. Prior to SQLite 3.42.0, any call to `sqlite3_config()` after SQLite had been initialized would result in a SQLITE_MISUSE error. Version 3.42.0 allows SQLITE_CONFIG_LOG to be used even after the library is initialized (see https://sqlite.org/releaselog/3_42_0.html).

**Comment by tserong** [comment]
@jecluis any objections if I put the latest sqlite3 release into https://build.opensuse.org/project/show/filesystems:ceph:s3gw to make these harmless but annoying error messages go away? (Note: the fix is in 3.42.0, but seeing as I'm proposing a version bump, I'd be inclined to go for 3.43.1, just because it's the most recent release)

**Comment by jecluis** [comment]
sure, upgrading seems fine. I'm a bit apprehensive that we will be updating that during the release window though. But maybe not having those silly little annoying messages is a good enough reason?

~(as a side note, realizing that upgrading this lib mid-release may be useful but potentially harmful, this just made me happier we now have it as a submodule all the more!)~

edit: nevermind, I'm still half asleep - I read that as sqlite orm instead of sqlite. My confidence level on sqlite is far greater, so I don't see a particular reason not to upgrade even during the release window, other than avoiding doing that as a general rule of thumb.

**Comment by tserong** [comment]
Alright, I'll hang back until after the current release, just for the sake of not setting a poor precedent :-)

**Comment by jecluis** [comment]
I wonder if we should fix the version in the dockerfile though. That would avoid this conundrum completely in the future.

**Comment by tserong** [comment]
> I wonder if we should fix the version in the dockerfile though. That would avoid this conundrum completely in the future.

Probably a good idea

**Comment by jecluis** [comment]
Alright, with this in mind I've filed https://github.com/aquarist-labs/s3gw/issues/725

**Comment by jecluis** [comment]
@tserong is this still a thing with the new library version?

**Comment by tserong** [comment]
> @tserong is this still a thing with the new library version?

All good, problem solved (sorry, I should have closed this earlier)
