### ISSUE TITLE
rgw/sfs: either drop or fix connection statistics from status page

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#726]
They don't work and we haven't looked at them, just drop them, they're clutter.

**Comment by irq0** [comment]
Holding for now - if we add a connection pool we can fix instead

**Comment by jecluis** [comment]
Adding to v0.23.0, by which time I hope we have figured out whether we remove or fix.

**Comment by jecluis** [comment]
won't deal with it because something else is fixing it (the connection pool thingy)
