### ISSUE TITLE
HA: ensure s3gw backend image is preloaded on every k8s node

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#734]
### What needs to be done

We need to ensure that the s3gw backend image is preloaded on every k8s node.
Failing to guarantee this implies that if the s3gw is scheduled to load on a node where the s3gw image is not cached, the system should pay the time needed to download the image from the registry before starting it.
In general on Kubernetes, it can not be assumed that an image is pre-pulled, since nodes may come and go dynamically.
Pre-pulled images is something we do want to ensure for eligible nodes. Otherwise, our restart is unpredictably long.
It's always possible that a fault occurs exactly at the time where we are pre-loading the image, but that's just bad luck.

### Why it needs to be done

This requirement is needed by the s3gw HA model: Active/Standby.

**Comment by giubacc** [comment]
cc @m-ildefons

**Comment by jecluis** [comment]
After checking with @l-mb and @m-ildefons , we believe it's better to push this to after v0.23.0. That frees @m-ildefons to focus on pushing for the initial version of LH controller without adding new requirements, and grants us time to figure out what's the best approach to deal with this.

**Comment by jecluis** [comment]
We believe this is no longer something we should focus on.
