### ISSUE TITLE
UI: about versioned buckets and versioned objects

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#744]
Currently, through the UI, for versioned buckets, isn't possible to delete a versioned object (meaning with versioned object an actual instance of an object with an associated versionId).
Instead, it is only possible to delete the `latest-version` object.

So:

`obj1.latest` <- can delete
`obj1.ver1` <- cannot delete
`obj1.ver2` <- cannot delete

I think it is important allowing the user to delete a specific version of an object via UI, because a version of an object could even take 1 zillionbyte of space, thus I would like to be able to delete it.

The DeleteObject API explicitly mentions the **null version**; I'm not entirely sure we are implementing a consistent semantics in s3gw with this API.

In our implementation `obj1.null` is a fake object that should not even exist because [we decided not to support the null object](https://github.com/aquarist-labs/s3gw/blob/main/docs/decisions/0010-sfs-versioning.md). 

The null object in S3 is the object with the associated `null` versionId. It is logically an instance version object with the same rules applied to all the other versions.

Depending on the API, S3 implicitly assume the null version OR the latest version when a version is not explicitly set in the query string.

The DeleteObject is an API assuming the null-version.

When we delete an object with the [DeleteObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html#API_DeleteObject_RequestSyntax) API and we don't specify the versionID we are deleting the null version and thus producing a DeleteMarker for the null version of the object.

Let's keep well in mind that **the null version CAN be the latest version at a certain point in time**.

Because the UI is reasoning as if the latest version of an object (either a regular version or a delete marker) were _more than simply another version_, and taking that version as root for querying all the other versions; we have the unpleasant effect that a DeleteMarker with an `isLatest==true` property, causes all the other versions to be hidden in the UI (you have to click on the deleted item checkbox, but some versions shown here could NOT be actually deleted).
This could be logically wrong, because an arbitrary version could (should ?) have the same dignity of the latest version.
I understand that this is controversial because having a "logical root object" facilitates the navigation into the bucket when you are using a web browser.
But I could argue that the latest version is, for all intents and purposes, just another version.

Now suppose that you have an object composed by 10 versions, everyone taking 1 TB of space, then you call DeleteObject without specifying the versionID; the backend treats this as the deletion of the null-version (?), it inserts a delete market for the null version (?) and in the UI there is no more evidence of such object because all the versions are hidden.
The user should go in the browser enable the show-deleted checkbox and search there for items that are NOT actually deleted, but only hidden.

## My proposal here is:

- **Drop the ban over the null version in the backend**, this will simplify all the edge cases; null version is just another version, I don't think it would be difficult, implementation speaking, using for example the `00000000-0000-0000-0000-000000000000` uid to identify that.
- **In the UI, don't give to the latest version the power it has now**, for versioned bucket display an entry if at least one version of the object (regardless if it is the latest) is alive. Give a deletion marker with the  `isLatest==true` property the importance it has now, IMO is too much.

**Comment by jecluis** [comment]
@giubacc after our chat earlier this week, do we still want to keep this issue around? Is there anything else to do here?

**Comment by giubacc** [comment]
In the end, I would only recommend to implement a specific `delete versionid ` feature in the UI.

**Comment by jecluis** [comment]
Okay, I'll close this issue then. Mind filing an issue for that?
