### ISSUE TITLE
[BUG] UI: make explicit description for default retention for buckets

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#748]
**Describe the bug** A clear and concise description of what the bug is.

Minor issue, but IMO worth to be addressed.
When creating a bucket and setting the default retention mode, I would make explicit that this is a _default retention mode_.
Let's keep in mind that this setting can be changed at any time. Also user can decide, explicitly, with the APIs to not even put a retention over an object (or/and over a specific version); that is completely optional.
Default retention mode only says that when there isn't an explicit setting from the user, the object takes the **current**  _default retention mode_.
The current description suggests that every object will take the retention set there.
So I would change that.

![image](https://github.com/aquarist-labs/s3gw/assets/99738959/e1416f97-e304-4656-9eb5-c59e40b9ed8b)

**Comment by votdev** [comment]
> The current description suggests that every object will take the retention set there.

Any suggestions on how to word the notice text instead?

**Comment by giubacc** [comment]
My suggestion, something like:

Title: "Default bucket retention mode"
SubTitle: "Applied to any object put without an explicit retention mode set"

**Comment by jecluis** [comment]
pushing to v0.23.0
