### ISSUE TITLE
Website: Needs to add "More from SUSE" in the navbar

### ISSUE THREAD

**Issue by vmoutoussamy** [s3gw-tech/s3gw#751]
All projects under https://opensource.suse.com have been asked to update their website to show a "More from SUSE" button.
Examples: 
- https://opensource.suse.com/bci/
  - Rancher, Epinio, Harvester, Kubewarden, Opni
- https://epinio.io/
  - Rancher, Harvester, Rancher Desktop, Opni, Kubewarden 

Deadline for this is Nov 4 (KubeCon)

**Comment by vmoutoussamy** [comment]
I suggest that our button should show the following: 
Longhorn, Rancher, Epinio, Harvester, Kubewarden

**Comment by jecluis** [comment]
This doesn't need to be associated with a milestone, but should be done by Nov 3, 2023.

**Comment by jecluis** [comment]
@jhmarina any progress on this?

**Comment by vmoutoussamy** [comment]
@jhmarina said in an email thread that he will do this before next week
