### ISSUE TITLE
[BUG] Documentation and website review

### ISSUE THREAD

**Issue by asettle** [s3gw-tech/s3gw#753]
**Describe the bug** Currently, the s3gw website appears to contain out-of-date information. For example: https://s3gw-docs.readthedocs.io/en/main/roadmap/ 

**Expected behavior** Before Kubecon Chicago (Nov 4-6), it would be good to ensure the website has up-to-date information or the out-of-date information is simply removed. We'd like to be able to highlight the LH and s3gw integration at this event, so it's important that our users are able to gather the most recent information.

**Screenshots** 
![Screenshot 2023-10-11 at 11 15 19](https://github.com/aquarist-labs/s3gw/assets/1987994/7f1199e9-bc0c-4aeb-b8cb-411f20f9ea95)

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/751
- [ ] https://github.com/aquarist-labs/s3gw/issues/779
```

**Comment by jecluis** [comment]
I believe this should be split into multiple issues, including but not limited to updating the roadmap, and the website update being handled by @jhmarina  (#751).
