### ISSUE TITLE
docs: explain how to use `--rgw-dns-name` to enable hostname style buckets

### ISSUE THREAD

**Issue by tserong** [s3gw-tech/s3gw#754]
This is already handled by the charts for k8s deployments, but for dev/test or standalone usage, we should document somewhere to run with `--rgw-dns-name YOUR_DOMAIN_NAME` in case hostname style bucket access is desired.  For example, in the ephemeral docker case you'd run something like this:

`docker run -p 7480:7480 quay.io/s3gw/s3gw:latest --rgw-backend-store sfs --debug-rgw 1 --rgw-dns-name YOUR_DOMAIN_NAME`

(This was originally reported on Slack at https://rancher-users.slack.com/archives/C04DCMUV8SE/p1696951336295009 when testing using a Java app using Amazon's S3Client class. This class apparently defaults to hostname style buckets, but can be made to using path style buckets by setting forcePathStyle = true.)

**Comment by jecluis** [comment]
For consistency with the project, I think this is the kind of thing that should also be wrapped by an entrypoint script. I kind of hate bleeing `rgw` options to the user.

**Comment by jecluis** [comment]
That and, when using the s3gw image, it should not be optional to use the `sfs` driver.

**Comment by tserong** [comment]
> That and, when using the s3gw image, it should not be optional to use the `sfs` driver.

100%
