### ISSUE TITLE
CI: Automate pruning shared docker resources

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#756]
One of our worker nodes went into disk pressure and took CI with it. 

Took CI with it? The actions runner controller scheduled a builder on the node with disk pressure. It went up fine, but was killed shortly before starting the build.

Why disk pressure? The shared docker directory blew up to 642G.

Quick fix: stop scheduling on the node. Attach a dockerd pod and run `docker system prune`:
Total reclaimed space: 292.2GB

Ideally this is a cronjob and a bit smarter. The prune also deleted shared resources that make the build faster.

**Comment by jecluis** [comment]
@Ameenasuhani is this something you can tackle?

**Comment by tserong** [comment]
Just hit (what I assume is) this again in https://github.com/aquarist-labs/ceph/actions/runs/6572126718/job/17853215667?pr=233

**Comment by jecluis** [comment]
there's already a workflow that does this
