### ISSUE TITLE
CRD based configuration of buckets and rbac (Epic)

### ISSUE THREAD

**Issue by agracey** [s3gw-tech/s3gw#76]
## Description
It might be useful to have an (optional) k8s operator that allows for basic control of buckets via CRDs. 

This would allow for setting up a [Crossplane](https://crossplane.io/) provider or [Epinio marketplace chart](https://docs.epinio.io/howtos/create_custom_service) to give a developer platform friendly way of consuming object storage for applications.

## Success criteria

An example user story (using Epinio since I know the flow best):
- Company is moving to object storage to allow for better horizontal scaling of applications and has chosen s3gw
- Platform Admin wants to provide a self service way of setting up a bucket
- In developer clusters, Admin creates an Epinio chart that contains the correct CRD to provision bucket and user and adds credentials into secret
- Developer sees new option in Epinio' service marketplace and provisions an instance (without touching k8s or s3gw. Or potentially even knowing they exist)
- Epinio creates CRD via helm which creates s3gw bucket [and user]
- Epinio mounts secret into application on next push
- Developer can now access their storage without needed to worry about it
- In production, the admin would create a bucket out of band (so as to not risk accidental deletion by poorly behaved automation...) and provide the secret directly.

## More information

```[tasklist]
### Tasks
- 
```

**Comment by Martin-Weiss** [comment]
Maybe this could also be based on something similar to https://rook.io/docs/rook/v1.10/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/

**Comment by m-ildefons** [comment]
There is prior art here and it seems likely that there is going to be an official API for this. So instead of building up a family of CRDs, we should probably engage with the wider K8s community:
https://container-object-storage-interface.github.io/

The object bucket claim from rook looks interesting, but iirc when I last looked at rook for this matter, there were some RGW specifics in there that we may want to avoid. Either way, it goes in the right direction and is definitively a good input to this discussion.

**Comment by giubacc** [comment]
@agracey We are addressing this topic with https://github.com/aquarist-labs/s3gw/issues/398.
Probably, once we have consolidated this implementation, it could be worth to discuss with the Epinio team for an use case of COSI in the Epinio context.
PS: starting from s3gw `0.16.0` (we are releasing now) COSI will be available for testing.

**Comment by giubacc** [comment]
I'm closing this since it is largely overlapped with https://github.com/aquarist-labs/s3gw/issues/398

**Comment by agracey** [comment]
👍
