### ISSUE TITLE
[BUG] rgw/sfs: default retention mode not applied to objects on multipart_upload_v2::complete

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#761]
[UPDATE] this is a backend issue.

`SFSMultipartUploadV2::complete()` does not perform the same updates on `attrs` made by `SFSAtomicWriter::complete`.
Specifically: the attribute `RGW_ATTR_OBJECT_RETENTION`  is not updated with the bucket's default retention mode. 

**Describe the bug** A clear and concise description of what the bug is.

After having created a bucket with a default retention mode:

![image](https://github.com/aquarist-labs/s3gw/assets/99738959/fb984f55-a7e9-4c88-923d-14b7d5ba7427)
 
Objects put in the bucket don't have the expected retention mode set:

![image](https://github.com/aquarist-labs/s3gw/assets/99738959/20df29fb-4ed7-42c3-9848-a8057f1c450f)

**Comment by votdev** [comment]
Can you confirm that the retention mode settings are NOT set on the bucket? If they are set correctly, then this is a `rgw/sfs` issue.

**Comment by giubacc** [comment]
I will double check; it can be a backed issue but it would be unlikely given that I'm using the same backend version used last week when I'm almost sure this was working.

**Comment by votdev** [comment]
> I will double check; it can be a backed issue but it would be unlikely given that I'm using the same backend version used last week when I'm almost sure this was working.

There were no relevant changes to the UI + REST API in the [last weeks](https://github.com/aquarist-labs/s3gw-ui/commits/main). So it must be a `rgw/sfs` issue.

**Comment by giubacc** [comment]
ok, I will do a complete analysis

**Comment by giubacc** [comment]
@votdev confirmed `rgw/sfs` issue; last week I was using the `PutObject` API, the UI is using the multipart upload API that fails to update the object lock attributes on the uploaded object.

**Comment by jecluis** [comment]
@giubacc do I understand you correctly: this is an sfs bug, not on the UI?

**Comment by giubacc** [comment]
> @giubacc do I understand you correctly: this is an sfs bug, not on the UI?

Exactly, my guess is that we should intervene on `SFSMultipartUploadV2::complete()` in the backend.
At the beginning I thought this was an UI issue, but then I did a complete analysis and the problem should be localized in the backend.

**Comment by jecluis** [comment]
do you have a reproducer script for this? something we can validate against?

**Comment by giubacc** [comment]
> do you have a reproducer script for this? something we can validate against?

This can be verified issuing an object multipart upload using the S3 APIs:

[CreateMultipartUpload](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html)
[UploadPart](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html)
[CompleteMultipartUpload](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html)

On the contrary, issuing a simple object upload with the S3 API:

[PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) 

does not produces the anomaly.
