### ISSUE TITLE
[FR] UI: implement delete function for a specific version of an object

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#764]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

We think is good to have in the UI a specific function to allow deletion of a single version instance of an object.
This request originates from https://github.com/aquarist-labs/s3gw/issues/744

**Comment by votdev** [comment]
What is purpose if this feature request? Do you want to allow users to cleanup the version history of an object and to be able to free disk space by deleting "archived" versions?

**Comment by votdev** [comment]
Do you want to support a `Bypass Governance Retention` checkbox to be able to delete object versions that are protected from deletion via retention mode? See [BypassGovernanceRetention](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/delete_object.html) flag.

**Comment by votdev** [comment]
What about a feature to cleanup the whole history by deleting all non-latest / non-current versions in a bunch? Does that make more sense from a users UX point of view?

**Comment by giubacc** [comment]
> What is purpose if this feature request? Do you want to allow users to cleanup the version history of an object and to be able to free disk space by deleting "archived" versions?

"archived" is a concept of our UI; an user could not agree on this; she could want to use all the versions of an object in her application.
She could therefore want to delete any version of an object.
Say why she could want to do that (delete a version) is hard to say, it is her business.

> Do you want to support a Bypass Governance Retention checkbox to be able to delete object versions that are protected from deletion via retention mode? See [BypassGovernanceRetention](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/delete_object.html) flag.

Yup, I would say that if a version is Governance protected, it could be useful to enable a Bypass function (if the user supports that function having the relative capability).

> What about a feature to cleanup the whole history by deleting all non-latest / non-current versions in a bunch? Does that make more sense from a users UX point of view?

Sure, that is a nice feature, but I would also give the ability to delete a single version for the reasons I said above.
