### ISSUE TITLE
UI: Instance Identification

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#765]
In cases where multiple instances of the s3gw are deployed in the same Longhorn cluster, it would be beneficial to have a clearly visible instance identification in the UI. The instance ID can be injected from e.g. an environment variable at deploy time and should be displayed on the landing/login page as well as the title bar.
At the moment there is no way other than the URL path to differentiate between multiple instances of the s3gw making multi-instance deployments confusing.

**Comment by jecluis** [comment]
This can be either a specific env variable with an instance id, like the object store name in the LH case, or we can start by reusing the already provided `S3GW_SERVICE_URL` and showing that somewhere in the UI. I lean towards the former, and default to the latter if an id is not provided.
