### ISSUE TITLE
UI: Add support for vhost style buckets

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#770]
Right now the UI supports path style buckets only. The support vhost style, there needs to be added a configuration to the Angular app and/or REST API to switch this feature on/off. Additionally a env variable needs to be added as well to be able to configure this on container level.

**Comment by jecluis** [comment]
Ideally this would not have to be configured on the UI. The UI should just "know", possibly obtaining such information from the s3gw service. In a LH environment, maybe even automatically configured by the controller (maybe through the env variable you mentioned).

I think we need to assess what is the most reasonable option here.

How much effort does it take to implement the vhost support on the UI, assuming the UI has the information about whether the service is using vhost-style buckets?

**Comment by votdev** [comment]
> Ideally this would not have to be configured on the UI. The UI should just "know", possibly obtaining such information from the s3gw service. In a LH environment, maybe even automatically configured by the controller (maybe through the env variable you mentioned).

This would be ideal, but it needs to be done somehow because boto3 needs to be configured correctly in that case.

```
s3={'addressing_style': 'virtual'}
```

> I think we need to assess what is the most reasonable option here.
> 
> How much effort does it take to implement the vhost support on the UI, assuming the UI has the information about whether the service is using vhost-style buckets?

The UI itself is independent from that, only the REST API needs to know.

**Comment by jecluis** [comment]
> > Ideally this would not have to be configured on the UI. The UI should just "know", possibly obtaining such information from the s3gw service. In a LH environment, maybe even automatically configured by the controller (maybe through the env variable you mentioned).
> 
> This would be ideal, but it needs to be done somehow because boto3 needs to be configured correctly in that case.
> 
> ```
> s3={'addressing_style': 'virtual'}
> ```

I'm thinking a specific s3gw operation, maybe an admin op, that provides that information? But I think this needs to be better fleshed out, for now we can probably rely on the controller to provide an env var to the s3gw-ui container.


> > I think we need to assess what is the most reasonable option here.
> > How much effort does it take to implement the vhost support on the UI, assuming the UI has the information about whether the service is using vhost-style buckets?
> 
> The UI itself is independent from that, only the REST API needs to know.

Good point. This should be reasonably simple to implement assuming an environment variable is provided.

**Comment by jecluis** [comment]
> > > Ideally this would not have to be configured on the UI. The UI should just "know", possibly obtaining such information from the s3gw service. In a LH environment, maybe even automatically configured by the controller (maybe through the env variable you mentioned).
> > 
> > 
> > This would be ideal, but it needs to be done somehow because boto3 needs to be configured correctly in that case.
> > ```
> > s3={'addressing_style': 'virtual'}
> > ```
> 
> I'm thinking a specific s3gw operation, maybe an admin op, that provides that information? But I think this needs to be better fleshed out, for now we can probably rely on the controller to provide an env var to the s3gw-ui container.

It just occurred to me, this would simply be another env var to be provided during Helm chart deployment. And if the user wants it standalone, they can also just provide said env var.

I really think env var is the way to go, no need to complicate things.
