### ISSUE TITLE
Update container base image

### ISSUE THREAD

**Issue by l-mb** [s3gw-tech/s3gw#771]
Currently, the s3gw container is built with leap:15.4 as the base image. This goes end of maintenance in November 2023.

s3gw should at least rebase to leap:15.5, or even consider utilizing the same base image as longhorn (https://github.com/longhorn/longhorn-instance-manager/blob/f80354ec9a09e986f378017410891b26dddecc00/package/Dockerfile#L1), which uses the sle-bci.

**Comment by tserong** [comment]
I've just tried doing this:

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,11 +1,11 @@
-FROM opensuse/leap:15.4 as s3gw-base
+FROM registry.suse.com/bci/bci-base:15.5 AS s3gw-base
 
 # This makes sure the Docker cache is invalidated
 # if packages in the s3gw repo on OBS have changed
-ADD https://download.opensuse.org/repositories/filesystems:/ceph:/s3gw/15.4/repodata/repomd.xml /tmp/
-# Add OBS repository for additional dependencies necessary on Leap 15.4
+ADD https://download.opensuse.org/repositories/filesystems:/ceph:/s3gw/SLE_15_SP5/repodata/repomd.xml /tmp/
+# Add OBS repository for additional dependencies necessary on SLE 15 SP5
 RUN zypper ar \
-  https://download.opensuse.org/repositories/filesystems:/ceph:/s3gw/15.4/ \
+  https://download.opensuse.org/repositories/filesystems:/ceph:/s3gw/SLE_15_SP5/ \
   s3gw-deps \
  && zypper --gpg-auto-import-keys ref
```

...which works fine to build the s3gw-base image. But then when we get on to the buildenv image, there's a handful of dependencies that aren't available in BCI:

```
No provider of 'gmock' found.
No provider of 'gtest' found.
No provider of 'librabbitmq-devel' found.
No provider of 'memory-constraints' found.
No provider of 're2-devel' found.
No provider of 'xmlstarlet' found.
Package 'lua53-luarocks' not found.
```

Some of these I can presumably get from some other devel repo on OBS, or I can just link them in to the filesystems:ceph:s3gw project. Also, this raises the question of whether we can drop any of these. For example, we don't build rgw's AMQP endpoint so presumably don't need librabbitmq-devel in the first place.

**Comment by l-mb** [comment]
The more we can drop/strip (and if need be, ifdef out), the less heavy our build would be, right? That's - in my opinion - a big win.

**Comment by tserong** [comment]
Right. Although I'm pretty sure we've already disabled everything we're not using (e.g.: AMQP as mentioned above), so all I'm finding here is extra packages that really don't need to be installed in the build environment.

**Comment by m-ildefons** [comment]
gmock/gtest is a requirement for our unit tests, so it can't be removed from the builds.
Lua isn't required by us specifically, but it's deeply engrained in the rgw code and requires quite a bit of #ifdef'ing to remove it
I presume that much like Lua, disabling the AMQP feature via compile time flag doesn't completely remove the dependency because if inconsistent #ifdefs around the depending code.

I still think it would be a nice thing to move to the BCI images.
