### ISSUE TITLE
chart: become rancher partner chart

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#78]
Become a [Rancher partner chart](https://github.com/rancher/partner-charts)

**Comment by abonillabeeche** [comment]
https://github.com/aquarist-labs/s3gw-charts/pull/25
should have enabled this - looks like the request needs to take place.

**Comment by jhmarina** [comment]
~~@m-ildefons if the issue was fixed in PR https://github.com/aquarist-labs/s3gw-charts/pull/25 can you close this issue?~~

**Comment by jhmarina** [comment]
☝ please disregard this comment

**Comment by jhmarina** [comment]
The team decided to close this issue & create a new epic where we'll add issues related to becoming a Rancher partner
