### ISSUE TITLE
[BUG] UI: try to delete an object-lock protected version causes the UI to exit to the login page

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#789]
**Describe the bug** A clear and concise description of what the bug is.

Trying to delete an object-lock protected version causes the UI to exit to the login page.
This does not happen for a versioned but not object protected object version.

![Peek 2023-10-30 17-38](https://github.com/aquarist-labs/s3gw/assets/99738959/6c69c55f-e9cb-4b5b-ade1-6a88162e911a)

I'd expect the UI to show the error message captured from the failed operation.

**Comment by votdev** [comment]
How have you set the `Governance` mode on the deleted object. The bucket has not specified that as default and the UI does not provide the ability to set that per object.

**Comment by giubacc** [comment]
An explicit retention on an object can be specified at least in 2 different ways: 

- directly with [PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html), specifying: 
```
        headers:
          x-amz-object-lock-mode: GOVERNANCE
          x-amz-object-lock-retain-until-date: "2024-07-07T13:40:15.949000000Z"
```
- deferred, first creating the obj and then putting on it a retention with [PutObjectRetention](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectRetention.html)

Obviously, you can rely on a default retention on the bucket and let that be applied automatically.
