### ISSUE TITLE
[BUG] Deleting an object using UI hit the error: validation error for DeletedObject

### ISSUE THREAD

**Issue by PhanLe1010** [s3gw-tech/s3gw#795]
**Describe the bug** A clear and concise description of what the bug is.

Deleting an object using UI hit the error: validation error for DeletedObject

**To Reproduce** Steps to reproduce the behavior:

1. Go to s3gw ui
2. Delete an object
3. See the error
    ```
      File "/srv/backend/api/objects.py", line 681, in <listcomp>
        DeletedObject.parse_obj(deleted) for deleted in s3_res["Deleted"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
      File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    pydantic.error_wrappers.ValidationError: 1 validation error for DeletedObject
    DeleteMarker
      field required (type=value_error.missing)
    ```

**Expected behavior** A clear and concise description of what you expected to
happen.

Deletion using UI should work

**Screenshots** If applicable, add screenshots to help explain your problem.

![Screenshot from 2023-11-06 21-57-56](https://github.com/aquarist-labs/s3gw/assets/22139961/fe4dc725-1550-4f25-ab40-537dbe1938ca)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu 22.04
- Browser [e.g. chrome, safari] Chrome
- Version 115.0.5790.170

s3gw version v0.22.0

**Comment by jecluis** [comment]
@votdev when you have a chance, please take a look at this.
