### ISSUE TITLE
Docs: HA with s3gw + LH    

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#803]
### What needs to be done

We conducted a first research on HA for s3gw + LH:  https://github.com/aquarist-labs/s3gw/issues/361
We are waiting for an input how to proceed with: https://github.com/longhorn/longhorn/issues/6803

Depending on decisions for the latter issue we will have to document how to enable the HA features with s3gw + LH

**Comment by jecluis** [comment]
We are no longer tackling LH-related things
