### ISSUE TITLE
[BUG] UI: Can't upload a file that was recently deleted

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#824]
**Describe the bug** A clear and concise description of what the bug is.

This was tested in a unversioned bucket.

Upload an object, delete it and try to upload the same object again. 
It won't upload the object.

Then you upload another object and retry to re-upload the previous object and you can upload it this time.

**Expected behavior** A clear and concise description of what you expected to
happen.

Be able to upload the object.

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/aquarist-labs/s3gw/assets/96239481/2870418c-36a6-45cd-91bd-bb3e469598c7

**Comment by votdev** [comment]
Not reproducible here
![Peek 2023-11-21 15-45](https://github.com/aquarist-labs/s3gw/assets/1897962/98957783-c9a6-423e-8548-64a98fb80989)

**Comment by jecluis** [comment]
I'm afraid I can't reproduce it either. @0xavi0 if you bump into this, lets reopen the issue. Until then, closing as invalid.
