### ISSUE TITLE
s3gw-chart: expose ingress url config

### ISSUE THREAD

**Issue by abonillabeeche** [s3gw-tech/s3gw#90]
Currently, no-tls is appended to the s3 endpoint and the UI. Ideally, we allow these URLs to be specified by the helm chart.

It's currently hardcoded as 
name: '{{ .Chart.Name }}-no-tls'
name: '{{ .Chart.Name }}-ui-tls'
... etc

**Comment by votdev** [comment]
This means you want to be able to configure the suffix of various resource names?

Examples:
- https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L7
- https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L33
- https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L56
- https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L82

**Comment by votdev** [comment]
I think what you want is to be able to configure the prefix of the host names.

Example:
hostname = foo

- [no-tls-foo](https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L40
)
- [ui-foo](https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L67)
- [no-tls-ui-foo](https://github.com/aquarist-labs/s3gw-charts/blob/main/charts/s3gw/templates/ingress-traefik.yaml#L89)
