### ISSUE TITLE
k3s: add the possibility to customize Longhorn default settings.

### ISSUE THREAD

**Issue by torchiaf** [s3gw-tech/s3gw#96]
- It should be possible to customize the default settings before to install s3gw in the cluster.
  Check the [docs](https://staging--longhornio.netlify.app/docs/1.0.2/advanced-resources/deploy/customizing-default-settings/#using-the-longhorn-deployment-yaml-file)
- Update docs.

**Comment by votdev** [comment]
Why is that needed? Which settings do you need to customize?

**Comment by jecluis** [comment]
@torchiaf mind explaining your motivation here?

**Comment by torchiaf** [comment]
@jecluis @votdev In case s3gw is installed using `setup.sh` script and the disk has few space left, the Longhorn persistent-volumes may not be mounted by s3gw pod.
This is because Longhorn requires at least 25% of free disk space, by default: [Longhorn docs](https://longhorn.io/docs/1.3.1/best-practices/#minimal-available-storage-and-over-provisioning).
It might be good to decrease that limit for users or anyone who wants to try the tool, without forcing them to make space on their machines.
This is the only reason I know for now but maybe, introducing the possibility to customize Longhorn will be usefull in the future.
What do you think guys?
